import React,{useEffect,useState} from 'react';
import {Check,Clipboard,Code2,Eye,EyeOff,RefreshCw,Send,ShieldCheck,Webhook} from 'lucide-react';
import {adminApi} from './api';

export default function AdminDeveloperTools(){
 const [credentials,setCredentials]=useState(null),[logs,setLogs]=useState([]),[busy,setBusy]=useState(''),[revealed,setRevealed]=useState({}),[notice,setNotice]=useState(''),[play,setPlay]=useState({endpoint:'/health'}),[result,setResult]=useState(null);
 const load=async()=>{try{const [c,l]=await Promise.all([adminApi('/api-settings/credentials'),adminApi('/api-settings/webhook/logs')]);setCredentials(c.credentials);setLogs(l.logs||[])}catch(e){setNotice(e.message)}};useEffect(()=>{load()},[]);
 const regen=async type=>{try{setBusy(type);const d=await adminApi('/api-settings/credentials/regenerate',{method:'POST',body:JSON.stringify({type})});setCredentials(x=>({...x,...d.credentials}));setRevealed(x=>({...x,[type]:true}));setNotice('New credential generated. Copy it now; it will not be shown again.')}catch(e){setNotice(e.message)}finally{setBusy('')}};
 const copy=async(v,label)=>{if(!v||String(v).startsWith('••'))return setNotice('Regenerate the credential to receive a copyable value.');try{await navigator.clipboard.writeText(v);setNotice(`${label} copied`)}catch{setNotice('Copy failed')}};
 const testWebhook=async()=>{try{setBusy('webhook');const d=await adminApi('/api-settings/webhook/test',{method:'POST'});setResult(d.result||d);const l=await adminApi('/api-settings/webhook/logs');setLogs(l.logs||[])}catch(e){setResult({success:false,message:e.message})}finally{setBusy('')}};
 const playground=async()=>{try{setBusy('play');const started=performance.now();const r=await fetch(`${String(import.meta.env.VITE_API_BASE_URL||'https://api.omniupi.in/api/v1').replace(/\/$/,'')}${play.endpoint}`);setResult({status:r.status,ms:Math.round(performance.now()-started),body:await r.text()})}catch(e){setResult({error:e.message})}finally{setBusy('')}};
 return <div className="two-col"><div><section className="panel"><h2>API Credentials</h2><p className="muted">Stored server-side. Existing credentials remain masked; regenerated values are shown once.</p>{[['token','API Token','apiToken'],['secret','Instance Secret','instanceSecret']].map(([type,title,key])=><div className="detail-row" key={type}><div><b>{title}</b><small>{credentials?.[key]||'••••••••••••••••'}</small></div><div className="actions"><button className="small-btn" onClick={()=>setRevealed(x=>({...x,[type]:!x[type]}))}>{revealed[type]?<EyeOff size={15}/>:<Eye size={15}/>}</button><button className="small-btn" onClick={()=>copy(credentials?.[key],title)}><Clipboard size={15}/></button><button className="small-btn" disabled={busy===type} onClick={()=>regen(type)}><RefreshCw size={15}/>{busy===type?'…':'Regenerate'}</button></div></div>)}</section><section className="panel"><div className="toolbar"><div><h2>API Test Playground</h2><p className="muted">Safe read-only endpoint checks.</p></div><Code2/></div><select value={play.endpoint} onChange={e=>setPlay({endpoint:e.target.value})}><option>/health</option><option>/api/v1</option></select><button className="primary" disabled={busy==='play'} onClick={playground}>{busy==='play'?'Testing…':'Send / Test'}</button>{result&&<pre style={{whiteSpace:'pre-wrap',marginTop:12,padding:12,background:'#f7f8fa',borderRadius:10}}>{result.error||result.body||JSON.stringify(result,null,2)}</pre>}</section></div><div><section className="panel"><div className="toolbar"><div><h2>Webhook Test</h2><p className="muted">Uses the existing HMAC/instance-secret signing mechanism. The secret never reaches the browser.</p></div><Webhook/></div><button className="primary" disabled={busy==='webhook'} onClick={testWebhook}><Send size={16}/>{busy==='webhook'?'Testing…':'Test Webhook'}</button>{result&&result.message&&<div className="status-box" style={{marginTop:12}}><b>{result.success?'SUCCESS':'FAILED'}</b> · HTTP {result.status||result.statusCode||'—'} · {result.responseTimeMs??'—'} ms<br/>{result.message}</div>}</section><section className="panel"><div className="toolbar"><div><h2>Webhook Delivery Logs</h2><p className="muted">No payloads, signatures or secrets are stored here.</p></div><ShieldCheck/></div>{logs.length?logs.map((l,i)=><div className="detail-row" key={l._id||i}><div><b>{l.event}</b><small>{l.orderId||'—'} · {new Date(l.deliveredAt).toLocaleString('en-IN')}</small></div><div><b>{l.success?'SUCCESS':'FAILED'}</b><small>HTTP {l.httpStatus||'—'} · {l.responseTimeMs??'—'} ms · {l.errorReason||'Delivered'}</small></div></div>):<div className="empty">No webhook deliveries recorded yet.</div>}</section></div></div>;
}
