(function(){
  const API_DOC_BASE='https://omniupi.in';
  const escDoc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const code=s=>`<pre class="doc-code"><button class="doc-copy" onclick="copyDoc(${JSON.stringify(String(s))})">Copy</button><code>${escDoc(s)}</code></pre>`;
  const pill=(t,c='')=>`<span class="doc-pill ${c}">${escDoc(t)}</span>`;
  const section=(icon,title,sub,body)=>`<section class="doc-section"><div class="doc-section-head"><span class="doc-icon">${icon}</span><div><h2>${title}</h2><p>${sub}</p></div></div>${body}</section>`;

  window.copyDoc=async function(text){try{await navigator.clipboard.writeText(text);toast('Copied to clipboard');}catch{toast('Copy failed — select and copy manually.')}};
  window.testDocHealth=async function(){const el=document.getElementById('doc-health');el.textContent='Checking…';try{const r=await fetch(API_DOC_BASE+'/api/health',{cache:'no-store'});const d=await r.json();el.innerHTML=`${pill('ONLINE','ok')} <span>${escDoc(d.service||'OmniUPI Public API')} · v${escDoc(d.version||'2.1')}</span>`;}catch(e){el.innerHTML=`${pill('OFFLINE','bad')} <span>Could not reach ${escDoc(API_DOC_BASE)}</span>`;}};
  window.testDocCreate=async function(){
    const amount=Number(document.getElementById('doc-amount').value), mobile=document.getElementById('doc-mobile').value.trim(), remark=document.getElementById('doc-remark').value.trim(), out=document.getElementById('doc-test-output');
    const token=localStorage.getItem('omniupi_token');
    if(!token){out.innerHTML='<div class="doc-alert bad">Login first. Your merchant API token is required.</div>';return;}
    if(!Number.isFinite(amount)||amount<=0){out.innerHTML='<div class="doc-alert bad">Enter a valid amount.</div>';return;}
    out.innerHTML='<div class="doc-alert">Creating a test order…</div>';
    try{const r=await fetch(API_DOC_BASE+'/api/create-order',{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify({amount,customer_mobile:mobile,remark1:remark})});const d=await r.json();if(!r.ok||d.status===false)throw new Error(d.message||'API request failed');out.innerHTML=`<div class="doc-result ok"><b>Order created successfully</b>${code(JSON.stringify(d,null,2))}<a class="doc-open" href="${escDoc(d.result?.paymentUrl||d.result?.payment_url||'#')}" target="_blank" rel="noopener">Open Payment Page →</a></div>`;}catch(e){out.innerHTML=`<div class="doc-alert bad">${escDoc(e.message)}</div>`;}
  };

  window.docsPage=async function(){
    const token=localStorage.getItem('omniupi_token')||'YOUR_API_TOKEN';
    const base=API_DOC_BASE;
    const curlCreate=`curl -X POST '${base}/api/create-order' \\\n  -H 'Authorization: Bearer ${token}' \\\n  -H 'Content-Type: application/json' \\\n  -d '{"amount":499,"customer_mobile":"9876543210","remark1":"Order 1001"}'`;
    const php=`<?php\n$apiUrl = '${base}/api/create-order';\n$payload = [\n  'amount' => 499,\n  'customer_mobile' => '9876543210',\n  'remark1' => 'Order 1001'\n];\n\n$ch = curl_init($apiUrl);\ncurl_setopt_array($ch, [\n  CURLOPT_RETURNTRANSFER => true,\n  CURLOPT_POST => true,\n  CURLOPT_HTTPHEADER => [\n    'Authorization: Bearer ${token}',\n    'Content-Type: application/json'\n  ],\n  CURLOPT_POSTFIELDS => json_encode($payload),\n  CURLOPT_TIMEOUT => 20\n]);\n$response = curl_exec($ch);\nif ($response === false) { throw new Exception(curl_error($ch)); }\ncurl_close($ch);\necho $response;\n?>`;
    const node=`const response = await fetch('${base}/api/create-order', {\n  method: 'POST',\n  headers: {\n    'Authorization': 'Bearer ${token}',\n    'Content-Type': 'application/json'\n  },\n  body: JSON.stringify({\n    amount: 499,\n    customer_mobile: '9876543210',\n    remark1: 'Order 1001'\n  })\n});\nconst data = await response.json();\nconsole.log(data);`;
    const python=`import requests\n\nurl = '${base}/api/create-order'\nheaders = {\n    'Authorization': 'Bearer ${token}',\n    'Content-Type': 'application/json'\n}\npayload = {\n    'amount': 499,\n    'customer_mobile': '9876543210',\n    'remark1': 'Order 1001'\n}\nresponse = requests.post(url, json=payload, headers=headers, timeout=20)\nprint(response.json())`;
    const statusCurl=`curl -X POST '${base}/api/check-order-status' \\\n  -H 'Authorization: Bearer ${token}' \\\n  -H 'Content-Type: application/json' \\\n  -d '{"order_id":"ORDER_ID"}'`;
    const webhook=`<?php\nif ($_SERVER['REQUEST_METHOD'] !== 'POST') {\n    http_response_code(405);\n    exit('Only POST requests are allowed');\n}\n\n$secret = 'YOUR_INSTANCE_SECRET';\n$rawBody = file_get_contents('php://input');\n$received = $_SERVER['HTTP_X_WEBHOOK_SIGNATURE'] ?? '';\n$expected = hash_hmac('sha256', $rawBody, $secret);\n\nif (!$received || !hash_equals($expected, $received)) {\n    http_response_code(401);\n    exit('Invalid Signature');\n}\n\n$data = json_decode($rawBody, true);\nif (($data['status'] ?? '') !== 'SUCCESS') {\n    http_response_code(400);\n    exit('Invalid status');\n}\n\n$orderId = $data['order_id'] ?? '';\n$amount  = $data['amount'] ?? '';\n$utr     = $data['utr'] ?? '';\n// Update your database/order here.\necho 'SUCCESS';\n?>`;

    app.innerHTML=`<div class="doc-shell">
      <div class="doc-hero"><div><div class="eyebrow">OMNIUPI DEVELOPER</div><h1>OmniUPI API Documentation</h1><p>Production-ready PayIN API reference for creating payment orders, checking status and receiving verified webhooks.</p><div class="doc-tags">${pill('REST API')} ${pill('JSON + form-urlencoded')} ${pill('HMAC-SHA256')} ${pill('UPI / INR')}</div></div><div class="doc-version">v2.1<br><small>Live API</small></div></div>
      <div class="doc-healthbar"><div><b>OmniUPI API Status</b><span id="doc-health">Checking…</span></div><button class="secondary" onclick="testDocHealth()">Check API</button></div>
      ${section('①','Quick Start','Create your first payment request in three steps.',`<div class="doc-steps"><div><b>1</b><strong>Connect merchant</strong><span>Add an active UPI merchant from Connect Merchant.</span></div><div><b>2</b><strong>Copy API credentials</strong><span>Use API Details to get your API Token and Instance Secret.</span></div><div><b>3</b><strong>Create an order</strong><span>Call the endpoint below and redirect the customer to payment_url.</span></div></div>`)}
      ${section('🔐','Authentication','Recommended authentication is Bearer token. The legacy user_token field is also supported for compatibility.',`<div class="doc-endpoint"><span class="method post">POST</span><b>${base}/api/create-order</b></div>${code(`Authorization: Bearer YOUR_API_TOKEN\nContent-Type: application/json`)}<div class="doc-note">Never expose your API token or Instance Secret in frontend JavaScript, mobile apps or public source code. Call the API from your secure backend.</div>`)}
      ${section('↗','Create Order','Create a pending PayIN order and receive a hosted payment page.',`<div class="doc-endpoint"><span class="method post">POST</span><b>${base}/api/create-order</b></div><table class="doc-table"><thead><tr><th>Parameter</th><th>Type</th><th>Required</th><th>Description</th></tr></thead><tbody><tr><td>amount</td><td>number</td><td>Yes</td><td>Amount in INR. Must be greater than 0.</td></tr><tr><td>customer_mobile</td><td>string</td><td>No</td><td>Customer mobile number.</td></tr><tr><td>merchant_id</td><td>string</td><td>No*</td><td>Specific connected merchant ID. If omitted, latest active merchant is used.</td></tr><tr><td>order_id</td><td>string</td><td>No</td><td>Your own unique order ID. Duplicate IDs are rejected.</td></tr><tr><td>redirect_url</td><td>URL</td><td>No</td><td>Redirect after successful hosted payment.</td></tr><tr><td>remark1</td><td>string</td><td>No</td><td>Product/order reference.</td></tr><tr><td>remark2</td><td>string</td><td>No</td><td>Additional reference.</td></tr></tbody></table><p class="doc-foot">*Required only when you have multiple merchants and want to select one.</p><h3>cURL</h3>${code(curlCreate)}<h3>PHP</h3>${code(php)}<h3>Node.js</h3>${code(node)}<h3>Python</h3>${code(python)}`)}
      ${section('✓','Successful Create Response','The API returns both camelCase and snake_case payment fields for easy integration.',code(JSON.stringify({status:true,message:'Order Created Successfully',result:{txnStatus:'PENDING',orderId:'123456789',order_id:'123456789',amount:'499.00',paymentUrl:`${base}/api/payment/123456789`,payment_url:`${base}/api/payment/123456789`,upiUrl:'upi://pay?...',upi_url:'upi://pay?...'}},null,2)))}
      ${section('⌕','Check Order Status','Poll from your backend or use the webhook for real-time confirmation.',`<div class="doc-endpoint"><span class="method post">POST</span><b>${base}/api/check-order-status</b></div><table class="doc-table"><thead><tr><th>Parameter</th><th>Type</th><th>Required</th></tr></thead><tbody><tr><td>order_id</td><td>string</td><td>Yes</td></tr></tbody></table>${code(statusCurl)}<h3>Success response</h3>${code(JSON.stringify({status:true,message:'Transaction Successfully',result:{txnStatus:'SUCCESS',orderId:'ORDER_ID',amount:'499.00',date:'2026-08-17T10:20:00.000Z',utr:'123456789012',remark1:'Order 1001',remark2:''}},null,2))}<div class="status-row">${pill('PENDING','pending')}${pill('SUCCESS','ok')} ${pill('FAILED','bad')} ${pill('EXPIRED','bad')}</div>`)}
      ${section('⚡','Live API Test','This sends a real API request to OmniUPI using your currently logged-in merchant token. It creates an actual pending order; no payment is charged until the customer pays.',`<div class="doc-test"><div class="form-grid"><div class="field"><label>Amount (₹)</label><input id="doc-amount" type="number" min="1" step="0.01" value="1"></div><div class="field"><label>Customer mobile</label><input id="doc-mobile" inputmode="numeric" value="9876543210"></div><div class="field full"><label>Remark</label><input id="doc-remark" value="OmniUPI Documentation Test Order"></div></div><button class="primary" onclick="testDocCreate()">Create Test Order</button><div id="doc-test-output"></div></div>`)}
      ${section('🔔','Webhook','When a payment becomes SUCCESS, OmniUPI sends a POST request to the webhook URL configured in your Account settings.',`<div class="doc-alert">Webhook is signed with HMAC-SHA256 using your Instance Secret and the exact raw JSON body. Always verify the signature before updating your order.</div><table class="doc-table"><thead><tr><th>Header</th><th>Value</th></tr></thead><tbody><tr><td>Content-Type</td><td>application/json</td></tr><tr><td>X-Webhook-Signature</td><td>HMAC-SHA256 hex signature</td></tr><tr><td>X-Webhook-Event</td><td>payment.success</td></tr></tbody></table>${code(JSON.stringify({status:'SUCCESS',order_id:'872431118',customer_mobile:'9876543210',amount:'499.00',utr:'2387476826',remark1:'Order 1001',remark2:'',timestamp:1786013741},null,2))}<h3>PHP verification handler</h3>${code(webhook)}`)}
      ${section('🧪','Integration Rules','Use these rules to avoid common production errors.',`<div class="doc-rules"><div><b>✓ Keep secrets server-side</b><span>API Token and Instance Secret must not be shipped to the browser.</span></div><div><b>✓ Save order_id</b><span>Store the returned order ID before redirecting the customer.</span></div><div><b>✓ Verify SUCCESS</b><span>Trust only a verified webhook or a successful status response for the same order ID.</span></div><div><b>✓ Match amount</b><span>Compare the returned amount with your original order amount.</span></div><div><b>✓ Make fulfillment idempotent</b><span>Process a successful order only once, even if webhook/status is received repeatedly.</span></div><div><b>✓ Use HTTPS</b><span>Your production webhook and redirect URLs should use HTTPS.</span></div></div>`)}
      ${section('⚠','Error Responses','All errors use a consistent JSON structure.',code(JSON.stringify({status:false,message:'Error message'},null,2))+`<table class="doc-table"><thead><tr><th>HTTP</th><th>Meaning</th></tr></thead><tbody><tr><td>400</td><td>Invalid request, amount, redirect URL or missing order_id.</td></tr><tr><td>401</td><td>Missing, invalid or inactive API token.</td></tr><tr><td>404</td><td>Order not found for this merchant.</td></tr><tr><td>409</td><td>Duplicate order_id.</td></tr><tr><td>500</td><td>Unexpected gateway error.</td></tr></tbody></table>`)}
      ${section('📋','Endpoint Summary','Keep this table beside your integration.',`<div class="doc-summary"><div><span class="method post">POST</span><b>${base}/api/create-order</b><small>Create PayIN order</small></div><div><span class="method post">POST</span><b>${base}/api/check-order-status</b><small>Check order status</small></div><div><span class="method get">GET</span><b>${base}/api/payment/{order_id}</b><small>Hosted customer payment page</small></div><div><span class="method get">GET</span><b>${base}/api/health</b><small>Public API health check</small></div></div>`)}
      <div class="doc-footer">OmniUPI · API v2.1 · Production documentation · <b>${base}</b></div>
    </div>`;
    testDocHealth();
  };
})();
