const app=document.getElementById('app'),crumb=document.getElementById('crumb'),sidebar=document.getElementById('sidebar');
const nav=document.querySelectorAll('#nav button');
let merchantsData=[{name:'Primary Store',email:'merchant@example.com',status:'Connected'},{name:'Demo Shop',email:'demo@example.com',status:'Pending'}];
const tx=[['TXN-10482','₹1,499.00','success','Today, 03:42 PM'],['TXN-10481','₹799.00','success','Today, 03:18 PM'],['TXN-10480','₹2,250.00','pending','Today, 02:57 PM'],['TXN-10479','₹349.00','failed','Today, 02:31 PM']];
function dashboard(){return `<div class="hero"><div><div class="eyebrow">PAYMENT INFRASTRUCTURE</div><h1>Dashboard</h1><p>Manage your payment gateway, merchants, orders and API integrations from one secure workspace.</p></div><button class="primary" onclick="show('Merchants');openMerchant()">＋ Add Merchant</button></div><div class="stats"><div class="stat"><span>Total Transactions</span><strong>12,480</strong><small>+12.4% this month</small></div><div class="stat"><span>Successful Payments</span><strong>11,936</strong><small>95.6% success rate</small></div><div class="stat"><span>Pending Payments</span><strong>128</strong><small>Needs verification</small></div><div class="stat"><span>Active Merchants</span><strong>${String(merchantsData.length).padStart(2,'0')}</strong><small>All systems normal</small></div></div><div class="grid"><div class="panel"><div class="panel-head"><div><h2>Payment overview</h2><p>Recent gateway activity</p></div><span class="badge success">Live</span></div><div class="chart"><div class="chart-line"></div></div></div><div class="panel"><div class="panel-head"><div><h2>Gateway status</h2><p>Live system health</p></div></div><div class="health"><span class="health-dot"></span><div><b>All systems operational</b><small>API, webhooks and payment services</small></div></div><div class="health-row"><span>API latency</span><b>82 ms</b></div><div class="health-row"><span>Webhook delivery</span><b>99.9%</b></div></div></div>`}
function merchants(){return `<div class="hero"><div><div class="eyebrow">ACCOUNT MANAGEMENT</div><h1>Merchants</h1><p>Add and manage payment merchants connected to your gateway.</p></div><button class="primary" onclick="openMerchant()">＋ Add Merchant</button></div><div class="table-panel"><div class="panel-head"><div><h2>Connected merchants</h2><p>${merchantsData.length} merchant account${merchantsData.length===1?'':'s'} configured</p></div></div>${merchantsData.map((m,i)=>`<div class="merchant-row"><div class="merchant-avatar">${escapeHtml(m.name[0])}</div><div><b>${escapeHtml(m.name)}</b><small>${escapeHtml(m.email)}</small></div><span class="badge ${m.status==='Connected'?'success':'pending'}">${m.status}</span><button class="secondary" onclick="manageMerchant(${i})">Manage</button></div>`).join('')}</div>`}
function transactions(){return `<div class="hero"><div><div class="eyebrow">PAYMENT ACTIVITY</div><h1>Transactions</h1><p>Track payment status, amount, UTR and transaction time.</p></div><button class="secondary" onclick="alert('Filters will be connected to the transaction API.')">Filter</button></div><div class="table-panel"><div class="txn-row head"><span>ID</span><span>Amount</span><span>Status</span><span>Time</span></div>${tx.map(t=>`<div class="txn-row"><span>${t[0]}</span><b>${t[1]}</b><span class="badge ${t[2]}">${t[2]}</span><small>${t[3]}</small></div>`).join('')}</div>`}
function links(){return `<div class="hero"><div><div class="eyebrow">CHECKOUT TOOLS</div><h1>Payment Links</h1><p>Create shareable checkout URLs for customers.</p></div><button class="primary" onclick="createLink()">＋ Create Link</button></div><div class="panel"><div class="link-card"><div><b>Demo Product</b><small>₹999.00 · Active</small></div><code>pay.example.com/l/demo-product</code><button class="icon-btn" onclick="copyText('pay.example.com/l/demo-product')">Copy</button></div><div class="link-card"><div><b>Premium Plan</b><small>₹1,499.00 · Active</small></div><code>pay.example.com/l/premium</code><button class="icon-btn" onclick="copyText('pay.example.com/l/premium')">Copy</button></div></div>`}
function api(){return `<div class="hero"><div><div class="eyebrow">DEVELOPER SETTINGS</div><h1>API & Webhooks</h1><p>Connect your server to the payment gateway API.</p></div></div><div class="settings-grid"><div class="panel"><h2>API credentials</h2><p>Keep credentials private and use them only on your server.</p><div class="secret"><code>••••••••••••••••••••••••</code><button onclick="alert('API credentials are managed securely by the backend.')">Manage</button></div></div><div class="panel"><h2>Webhook endpoint</h2><p>Receive signed payment events after successful payments.</p><div class="input-like">https://your-domain.com/api/webhook</div><button class="secondary" onclick="alert('Endpoint will be saved through the backend API.')">Save endpoint</button></div></div>`}
function security(){return `<div class="hero"><div><div class="eyebrow">PROTECTION</div><h1>Security</h1><p>Protect your merchant account and webhook integrations.</p></div></div><div class="settings-grid"><div class="panel"><h2>Account security</h2><p>Recommended protections for your account.</p><div class="health"><span class="health-dot"></span><div><b>Security checks enabled</b><small>Use strong passwords and secure backend secrets.</small></div></div><div class="toggle-row"><span>Login notifications</span><button class="toggle on" onclick="toggle(this)"><i></i></button></div></div><div class="panel"><h2>Webhook signing</h2><p>Verify X-Webhook-Signature on the backend before processing payment notifications.</p><span class="badge success">HMAC-SHA256 ready</span><div class="input-like">Webhook secret: ••••••••••••••••</div></div></div>`}
function settings(){return `<div class="hero"><div><div class="eyebrow">ACCOUNT PREFERENCES</div><h1>Settings</h1><p>Manage account preferences and gateway defaults.</p></div></div><div class="settings-grid"><div class="panel"><h2>Business profile</h2><p>Basic merchant information.</p><div class="input-like">Merchant account</div><div class="input-like">merchant@example.com</div><button class="secondary" onclick="alert('Settings will be saved through the backend API.')">Save changes</button></div><div class="panel"><h2>Notifications</h2><p>Payment event notifications.</p><div class="toggle-row"><span>Successful payments</span><button class="toggle on" onclick="toggle(this)"><i></i></button></div><div class="toggle-row"><span>Failed payments</span><button class="toggle on" onclick="toggle(this)"><i></i></button></div><div class="toggle-row"><span>Weekly reports</span><button class="toggle" onclick="toggle(this)"><i></i></button></div></div></div>`}
function show(page){nav.forEach(b=>b.classList.toggle('active',b.dataset.page===page));crumb.textContent=page;const views={Dashboard:dashboard,Merchants:merchants,'Payment Links':links,Transactions:transactions,'API & Webhooks':api,Security:security,Settings:settings};app.innerHTML=views[page]();sidebar.classList.remove('open');window.scrollTo({top:0,behavior:'smooth'})}
function openMerchant(){document.getElementById('merchantModal').classList.add('show');setTimeout(()=>document.getElementById('upiId')?.focus(),50)}
function closeMerchant(){document.getElementById('merchantModal').classList.remove('show')}
function createLink(){alert('Create Payment Link UI is ready. The final link will be created by the backend payment-link API.')}
function manageMerchant(i){const m=merchantsData[i];alert(`${m.name}\nStatus: ${m.status}\n${m.email}`)}
function googleConnect(){alert('Google OAuth must be completed by the backend. Never enter or store a Gmail password or App Password on this page.')}
function saveMerchant(){const u=document.getElementById('upiId').value.trim(),m=document.getElementById('mobile').value.replace(/\D/g,''),n=document.getElementById('merchantName').value.trim();if(!u||!m||!n)return alert('UPI ID, mobile number and merchant name are required.');if(m.length!==10)return alert('Enter a valid 10-digit mobile number.');merchantsData.push({name:n,email:u,status:'Pending'});closeMerchant();show('Merchants');alert('Merchant added to the UI as Pending. Real account connection requires the backend + approved OAuth/payment integration.')}
function toggle(el){el.classList.toggle('on')}
function copyText(v){navigator.clipboard?.writeText(v);alert('Copied')}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
nav.forEach(b=>b.onclick=()=>show(b.dataset.page));document.getElementById('menu').onclick=()=>sidebar.classList.toggle('open');
document.body.insertAdjacentHTML('beforeend',`<div id="merchantModal" class="modal" role="dialog" aria-modal="true" aria-labelledby="merchantTitle"><div class="modal-card"><button class="modal-close" aria-label="Close" onclick="closeMerchant()">×</button><div class="eyebrow">CONNECT MERCHANT</div><h2 id="merchantTitle">Add Merchant</h2><p class="modal-sub">Enter basic merchant details. Authentication is completed securely through OAuth; never enter a Gmail password here.</p><label>UPI ID<input id="upiId" autocomplete="off" placeholder="merchant@upi"></label><label>Registered Mobile Number<input id="mobile" inputmode="numeric" maxlength="10" autocomplete="tel" placeholder="10-digit mobile number"></label><label>Merchant Name<input id="merchantName" autocomplete="organization" placeholder="Business / merchant name"></label><div class="google-box"><b>Google account verification</b><small>Use the Google account linked to the merchant/payment account.</small><button class="secondary" onclick="googleConnect()">G&nbsp; Continue with Google</button></div><button class="primary wide" onclick="saveMerchant()">Continue &amp; Connect</button></div></div>`);
document.getElementById('merchantModal').addEventListener('click',e=>{if(e.target.id==='merchantModal')closeMerchant()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMerchant()});app.innerHTML=dashboard();