(()=>{
const API='https://api.omniupi.in';
const token=localStorage.getItem('omniupi_token');
if(!token)return;
const req=async(path,opts={})=>{const r=await fetch(API+path,{...opts,headers:{Accept:'application/json','Content-Type':'application/json',Authorization:`Bearer ${token}`,...(opts.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok||d.status===false)throw new Error(d.message||`Request failed (${r.status})`);return d};
const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const money=n=>'₹'+Number(n||0).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2});
function toast(m){window.toast?window.toast(m):alert(m)}
const oldBuy=window.buyPlan;
window.buyPlan=async id=>{try{const d=await req('/api/v1/subscriptions/purchase',{method:'POST',body:JSON.stringify({planId:id})});const o=d.order;const style=`<style id="sub-pay-css">.sp-card{width:min(430px,100%);background:#fff;border-radius:22px;padding:22px;box-sizing:border-box}.sp-head{text-align:center}.sp-qr{width:230px;height:230px;display:block;margin:15px auto;border-radius:14px;border:1px solid #e8ebf0}.sp-upi{background:#f7f9fb;border:1px solid #e7ebf0;border-radius:12px;padding:11px;font-size:11px}.sp-upi b{display:block;font-size:14px;margin-bottom:3px}.sp-note{margin-top:12px;padding:11px;border-radius:11px;background:#fff9e8;border:1px solid #f1df9d;color:#7d6416;font-size:11px;line-height:1.5}.sp-status{margin-top:12px;padding:11px;border-radius:11px;text-align:center;background:#f7f9fb;font-size:11px}.sp-ok{background:#effbf6;color:#167354;border-color:#bfe8d8}.sp-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:13px}.sp-actions a,.sp-actions button{flex:1;min-width:140px;justify-content:center;text-align:center}</style>`;document.head.insertAdjacentHTML('beforeend',style);document.body.insertAdjacentHTML('beforeend',`<div class="modal show" id="subPaymentModal"><div class="modal-card" style="max-width:480px"><button class="modal-close" onclick="closeModal('subPaymentModal')">×</button><div class="sp-card"><div class="sp-head"><div class="eyebrow">SUBSCRIPTION PAYMENT</div><h2>${esc(o.plan)}</h2><p class="modal-sub">Pay <b>${money(o.amount)}</b> to the verified OmniUPI payment UPI.</p></div><img class="sp-qr" src="${esc(o.qrDataUrl)}" alt="UPI payment QR"><div class="sp-upi"><b>${esc(o.upiName)}</b>${esc(o.upiId)}<div style="margin-top:7px">Order: ${esc(o.orderId)}</div></div><div class="sp-note">Scan this QR with any supported UPI app, or tap <b>Open UPI App</b>. Keep this page open while payment is being verified.</div><div id="spStatus" class="sp-status">Waiting for payment…</div><div class="sp-actions"><a class="primary" href="${esc(o.paymentUrl)}" style="text-decoration:none">Open UPI App</a><button class="secondary" id="spRefresh">Check Payment</button><button class="secondary" onclick="closeModal('subPaymentModal')">Close</button></div></div></div></div>`);const statusEl=document.getElementById('spStatus');let busy=false;const check=async()=>{if(busy)return;busy=true;try{const x=await req(`/api/v1/subscriptions/order/${encodeURIComponent(o.orderId)}`);if(x.order.status==='SUCCESS'){statusEl.textContent='✓ Payment received. Subscription activated.';statusEl.className='sp-status sp-ok';toast('Payment received. Subscription activated.');clearInterval(timer)}else statusEl.textContent='Payment not confirmed yet. Scan/pay and check again.'}catch(e){statusEl.textContent=e.message}finally{busy=false}};document.getElementById('spRefresh').onclick=check;const timer=setInterval(check,4000)}catch(e){toast(e.message)}};
})();