import { Router } from 'express';
import bcrypt from 'bcryptjs';
import crypto from 'crypto';
import Plan from '../models/Plan.js';
import GatewaySettings from '../models/GatewaySettings.js';
import KycOrder from '../models/KycOrder.js';
import User from '../models/User.js';
import Order from '../models/Order.js';
import Merchant from '../models/Merchant.js';
import SubscriptionOrder from '../models/SubscriptionOrder.js';
import SupportTicket from '../models/SupportTicket.js';
import GmailConnection from '../models/GmailConnection.js';
import { requireAuth, requireAdmin } from '../middleware/auth.js';
import { encryptSecret } from '../utils/secretBox.js';

const router = Router();
router.use(requireAuth, requireAdmin);
const newApiToken = () => `ag_live_${crypto.randomBytes(32).toString('hex')}`;
const newInstanceSecret = () => `ag_sec_${crypto.randomBytes(32).toString('hex')}`;
const envAdminEmail = () => String(process.env.ADMIN_EMAIL || '').trim().toLowerCase();
const dayStart = d => { const x = new Date(d); x.setHours(0,0,0,0); return x; };
function dateRange(req) {
  const now = new Date();
  if (req.query.from || req.query.to) { const from = req.query.from ? new Date(req.query.from) : new Date(now.getTime() - 30*86400000); const to = req.query.to ? new Date(req.query.to) : now; if (Number.isNaN(from.getTime()) || Number.isNaN(to.getTime())) return null; to.setHours(23,59,59,999); return {from,to}; }
  const range = String(req.query.range || '7d').toLowerCase();
  const today = dayStart(now);
  if (range === 'yesterday') return {from:new Date(today.getTime()-86400000),to:new Date(today.getTime()-1)};
  const days = range === 'today' ? 0 : range === '30d' ? 29 : 6;
  return {from:new Date(today.getTime()-days*86400000),to:now};
}
function safeSettings(s) { const obj=s?.toObject?s.toObject():{...(s||{})}; delete obj.googleClientSecretEncrypted; obj.googleClientSecretConfigured=!!s?.googleClientSecretEncrypted; return obj; }

router.get('/dashboard', async (req,res,next)=>{try{
  const range=dateRange(req); if(!range)return res.status(400).json({status:false,message:'Invalid date range'}); const today=dayStart(new Date()); const base={role:'merchant'};
  const [totalUsers,joinedToday,activeUsers,suspendedUsers,totalMerchants,activeMerchants,totalOrders,pendingOrders,successfulOrders,failedOrders,todayOrders,todayUsers,todayMerchants,pendingKyc,verifiedKyc,activePlans,supportTickets,revenue,todayRevenue,userSeries,orderSeries]=await Promise.all([
    User.countDocuments(base),User.countDocuments({...base,createdAt:{$gte:today}}),User.countDocuments({...base,status:'active'}),User.countDocuments({...base,status:'suspended'}),Merchant.countDocuments(),Merchant.countDocuments({status:'active'}),Order.countDocuments(),Order.countDocuments({status:'PENDING'}),Order.countDocuments({status:'SUCCESS'}),Order.countDocuments({status:'FAILED'}),Order.countDocuments({createdAt:{$gte:today}}),User.countDocuments({...base,createdAt:{$gte:today}}),Merchant.countDocuments({createdAt:{$gte:today}}),KycOrder.countDocuments({status:'SUBMITTED'}),KycOrder.countDocuments({status:'VERIFIED'}),Plan.countDocuments({active:true}),SupportTicket.countDocuments({status:{$nin:['closed','resolved']}}),
    Order.aggregate([{$match:{status:'SUCCESS'}},{$group:{_id:null,total:{$sum:'$amount'},net:{$sum:'$netAmount'},fees:{$sum:'$feeAmount'}}}]),Order.aggregate([{$match:{status:'SUCCESS',createdAt:{$gte:today}}},{$group:{_id:null,total:{$sum:'$amount'},net:{$sum:'$netAmount'},fees:{$sum:'$feeAmount'}}}]),
    User.aggregate([{$match:{...base,createdAt:{$gte:range.from,$lte:range.to}}},{$group:{_id:{$dateToString:{format:'%Y-%m-%d',date:'$createdAt'}},count:{$sum:1}}},{$sort:{_id:1}}]),
    Order.aggregate([{$match:{createdAt:{$gte:range.from,$lte:range.to}}},{$group:{_id:{$dateToString:{format:'%Y-%m-%d',date:'$createdAt'}},orders:{$sum:1},amount:{$sum:'$amount'},success:{$sum:{$cond:[{$eq:['$status','SUCCESS']},1,0]}},failed:{$sum:{$cond:[{$eq:['$status','FAILED']},1,0]}},revenue:{$sum:'$feeAmount'}}},{$sort:{_id:1}}])
  ]);
  res.json({status:true,stats:{totalUsers,joinedToday,activeUsers,suspendedUsers,totalMerchants,activeMerchants,totalOrders,pendingOrders,successfulOrders,failedOrders,todayOrders,todayUsers,todayMerchants,pendingKyc,verifiedKyc,activePlans,supportTickets,totalTransactionAmount:revenue[0]?.total||0,todayTransactionAmount:todayRevenue[0]?.total||0,totalRevenue:revenue[0]?.fees||0,todayRevenue:todayRevenue[0]?.fees||0},charts:{users:userSeries,transactions:orderSeries}});
}catch(e){next(e)}});
router.get('/stats', async(req,res,next)=>{try{const range=req.query.range||'today';req.query.range=range;const fake={query:req.query};const start=range==='today'?dayStart(new Date()):range==='yesterday'?new Date(dayStart(new Date()).getTime()-86400000):new Date(Date.now()-7*86400000);const [totalUsers,todayUsers,totalOrders,todayOrders,successfulOrders,pendingOrders,totalMerchants,activeMerchants,pendingKyc,adminCount,revenue]=await Promise.all([User.countDocuments({role:'merchant'}),User.countDocuments({role:'merchant',createdAt:{$gte:dayStart(new Date())}}),Order.countDocuments(),Order.countDocuments({createdAt:{$gte:dayStart(new Date())}}),Order.countDocuments({status:'SUCCESS'}),Order.countDocuments({status:'PENDING'}),Merchant.countDocuments(),Merchant.countDocuments({status:'active'}),KycOrder.countDocuments({status:'SUBMITTED'}),User.countDocuments({role:'admin'}),Order.aggregate([{$match:{status:'SUCCESS'}},{$group:{_id:null,total:{$sum:'$amount'},net:{$sum:'$netAmount'},fees:{$sum:'$feeAmount'}}}])]);res.json({status:true,stats:{totalUsers,todayUsers,activeUsers:await User.countDocuments({role:'merchant',status:'active'}),totalOrders,todayOrders,successfulOrders,pendingOrders,totalMerchants,activeMerchants,pendingKyc,adminCount,revenue:revenue[0]||{total:0,net:0,fees:0},rangeStart:start},charts:{}});}catch(e){next(e)}});

router.get('/users',async(req,res,next)=>{try{const page=Math.max(Number(req.query.page)||1,1),limit=Math.min(Math.max(Number(req.query.limit)||25,1),100),q=String(req.query.search||'').trim();const filter={role:'merchant'};if(q)filter.$or=[{name:new RegExp(q,'i')},{email:new RegExp(q,'i')},{userId:new RegExp(q,'i')},{mobile:new RegExp(q,'i')}];if(['active','suspended'].includes(req.query.status))filter.status=req.query.status;if(['NOT_SUBMITTED','PENDING_PAYMENT','PENDING_REVIEW','VERIFIED','REJECTED'].includes(req.query.kycStatus))filter.kycStatus=req.query.kycStatus;if(['NONE','ACTIVE','EXPIRED'].includes(req.query.planStatus))filter.planStatus=req.query.planStatus;const sort=String(req.query.sort||'newest')==='oldest'?{createdAt:1}:{createdAt:-1};const [users,total]=await Promise.all([User.find(filter).select('name email userId mobile companyName status kycStatus webhookUrl whitelistedIps createdAt updatedAt trialEndsAt planStartedAt planExpiresAt planStatus authProvider').populate('plan','name price durationDays transactionFeePercent').sort(sort).skip((page-1)*limit).limit(limit).lean(),User.countDocuments(filter)]);res.json({status:true,users,pagination:{page,limit,total,pages:Math.ceil(total/limit)}});}catch(e){next(e)}});
router.get('/users/:id',async(req,res,next)=>{try{const user=await User.findOne({_id:req.params.id,role:'merchant'}).select('-passwordHash -apiToken -instanceSecret').populate('plan','name price durationDays transactionFeePercent features').lean();if(!user)return res.status(404).json({status:false,message:'User not found'});const [merchantCount,orderCount,success]=await Promise.all([Merchant.countDocuments({owner:user._id}),Order.countDocuments({owner:user._id}),Order.aggregate([{$match:{owner:user._id,status:'SUCCESS'}},{$group:{_id:null,count:{$sum:1},amount:{$sum:'$amount'},fees:{$sum:'$feeAmount'}}}])]);res.json({status:true,user,stats:{merchantCount,orderCount,...(success[0]||{count:0,amount:0,fees:0})},orders:await Order.find({owner:user._id}).sort({createdAt:-1}).limit(25).populate('merchant','name upiId status').lean()});}catch(e){next(e)}});
router.patch('/users/:id',async(req,res,next)=>{try{const allowed=['status','kycStatus','plan','planStatus','planExpiresAt','webhookUrl','name','mobile','companyName','location'];const patch=Object.fromEntries(allowed.filter(k=>k in req.body).map(k=>[k,req.body[k]]));if(patch.status&&!['active','suspended'].includes(patch.status))return res.status(400).json({status:false,message:'Invalid user status'});if('webhookUrl'in patch&&patch.webhookUrl&&!/^https?:\/\//i.test(patch.webhookUrl))return res.status(400).json({status:false,message:'Webhook URL must include http or https'});const user=await User.findOneAndUpdate({_id:req.params.id,role:'merchant'},patch,{new:true,runValidators:true}).select('name email userId status kycStatus planStatus planExpiresAt webhookUrl mobile companyName location');if(!user)return res.status(404).json({status:false,message:'User not found'});res.json({status:true,user});}catch(e){next(e)}});
router.post('/users/:id/reset-password',async(req,res,next)=>{try{const password=String(req.body.password||'');if(password.length<8)return res.status(400).json({status:false,message:'Password must be at least 8 characters'});const user=await User.findOne({_id:req.params.id,role:'merchant'});if(!user)return res.status(404).json({status:false,message:'User not found'});user.passwordHash=await bcrypt.hash(password,12);await user.save();res.json({status:true,message:'Password reset successfully'});}catch(e){next(e)}});
router.post('/users/:id/regenerate-credentials',async(req,res,next)=>{try{const type=String(req.body.type||'').toLowerCase();if(!['token','secret','both'].includes(type))return res.status(400).json({status:false,message:'Invalid credential type'});const user=await User.findOne({_id:req.params.id,role:'merchant'}).select('+apiToken +instanceSecret userId');if(!user)return res.status(404).json({status:false,message:'User not found'});if(type==='token'||type==='both')user.apiToken=newApiToken();if(type==='secret'||type==='both')user.instanceSecret=newInstanceSecret();await user.save({validateBeforeSave:false});res.json({status:true,message:'Credentials regenerated successfully',credentials:{userId:user.userId,apiToken:user.apiToken,instanceSecret:user.instanceSecret}});}catch(e){next(e)}});
router.get('/users/:id/api',async(req,res,next)=>{try{const user=await User.findOne({_id:req.params.id,role:'merchant'}).select('+apiToken +instanceSecret userId webhookUrl whitelistedIps');if(!user)return res.status(404).json({status:false,message:'User not found'});res.json({status:true,credentials:{userId:user.userId,apiToken:user.apiToken||'',instanceSecret:user.instanceSecret||'',webhookUrl:user.webhookUrl||'',whitelistedIps:user.whitelistedIps||[]}});}catch(e){next(e)}});

router.get('/merchants',async(req,res,next)=>{try{const q=String(req.query.search||'').trim();const filter=q?{$or:[{name:new RegExp(q,'i')},{upiId:new RegExp(q,'i')},{mobile:new RegExp(q,'i')},{provider:new RegExp(q,'i')}]}:{};res.json({status:true,merchants:await Merchant.find(filter).populate('owner','name email userId').sort({createdAt:-1}).limit(Math.min(Number(req.query.limit)||100,500)).lean()});}catch(e){next(e)}});
router.patch('/merchants/:id',async(req,res,next)=>{try{const patch={};if(['pending','active','paused','error'].includes(req.body.status))patch.status=req.body.status;if(['pending','verifying','verified','failed'].includes(req.body.verificationStatus))patch.verificationStatus=req.body.verificationStatus;const m=await Merchant.findByIdAndUpdate(req.params.id,patch,{new:true}).populate('owner','name email userId');if(!m)return res.status(404).json({status:false,message:'Merchant not found'});res.json({status:true,merchant:m});}catch(e){next(e)}});

router.get('/orders',async(req,res,next)=>{try{const limit=Math.min(Math.max(Number(req.query.limit)||100,1),500);const q=String(req.query.search||'').trim();const filter={};if(['PENDING','SUCCESS','FAILED','EXPIRED'].includes(req.query.status))filter.status=req.query.status;if(q)filter.$or=[{orderId:new RegExp(q,'i')},{customerMobile:new RegExp(q,'i')},{utr:new RegExp(q,'i')}];if(req.query.merchant)filter.merchant=req.query.merchant;if(req.query.from||req.query.to){filter.createdAt={};if(req.query.from)filter.createdAt.$gte=new Date(req.query.from);if(req.query.to){const to=new Date(req.query.to);to.setHours(23,59,59,999);filter.createdAt.$lte=to;}}res.json({status:true,orders:await Order.find(filter).populate('owner','name email userId').populate('merchant','name upiId status provider').sort({createdAt:-1}).limit(limit).lean()});}catch(e){next(e)}});
router.get('/orders/:id',async(req,res,next)=>{try{const order=await Order.findOne({$or:[{_id:req.params.id},{orderId:req.params.id}]}).populate('owner','name email userId mobile companyName').populate('merchant','name upiId status provider mobile verificationStatus').lean();if(!order)return res.status(404).json({status:false,message:'Order not found'});res.json({status:true,order});}catch(e){next(e)}});

router.get('/plans',async(_req,res,next)=>{try{const plans=await Plan.find().sort({price:1}).lean();const counts=await SubscriptionOrder.aggregate([{$match:{status:'SUCCESS',planExpiresAt:{$gt:new Date()}}},{$group:{_id:'$plan',count:{$sum:1}}}]);const map=new Map(counts.map(x=>[String(x._id),x.count]));res.json({status:true,plans:plans.map(p=>({...p,subscribers:map.get(String(p._id))||0}))});}catch(e){next(e)}});
router.post('/plans',async(req,res,next)=>{try{const {name,price,durationDays,transactionLimit,merchantLimit,apiAccess,transactionFeePercent,features,active,popular}=req.body;if(!name||Number(price)<0||Number(durationDays)<1)return res.status(400).json({status:false,message:'name, price and durationDays are required'});const plan=await Plan.create({name:String(name).trim(),price:Number(price),durationDays:Number(durationDays),transactionLimit:Number(transactionLimit)||0,merchantLimit:Number(merchantLimit)||1,apiAccess:apiAccess!==false,transactionFeePercent:Number(transactionFeePercent)||0,features:Array.isArray(features)?features:[],active:active!==false,popular:Boolean(popular)});res.status(201).json({status:true,plan});}catch(e){next(e)}});
router.put('/plans/:id',async(req,res,next)=>{try{const allowed=['name','price','durationDays','transactionLimit','merchantLimit','apiAccess','transactionFeePercent','features','active','popular'];const patch=Object.fromEntries(allowed.filter(k=>k in req.body).map(k=>[k,req.body[k]]));const plan=await Plan.findByIdAndUpdate(req.params.id,patch,{new:true,runValidators:true});if(!plan)return res.status(404).json({status:false,message:'Plan not found'});res.json({status:true,plan});}catch(e){next(e)}});
router.delete('/plans/:id',async(req,res,next)=>{try{const plan=await Plan.findById(req.params.id);if(!plan)return res.status(404).json({status:false,message:'Plan not found'});plan.active=false;await plan.save();res.json({status:true,message:'Plan deactivated'});}catch(e){next(e)}});

router.get('/kyc',async(_req,res,next)=>{try{const requests=await KycOrder.find({status:{$in:['SUBMITTED','REJECTED','VERIFIED']}}).sort({submittedAt:-1}).limit(300).populate('user','userId name email mobile companyName kycStatus').select('orderId amount status submittedAt paidAt rejectionReason user');res.json({status:true,requests});}catch(e){next(e)}});
router.post('/kyc/:id/verify',async(req,res,next)=>{try{const request=await KycOrder.findById(req.params.id);if(!request)return res.status(404).json({status:false,message:'KYC request not found'});request.status='VERIFIED';request.verifiedAt=new Date();request.rejectionReason='';await request.save();await User.findByIdAndUpdate(request.user,{kycStatus:'VERIFIED',kycVerifiedAt:request.verifiedAt});res.json({status:true,message:'KYC verified successfully',verifiedAt:request.verifiedAt});}catch(e){next(e)}});
router.post('/kyc/:id/reject',async(req,res,next)=>{try{const request=await KycOrder.findById(req.params.id);if(!request)return res.status(404).json({status:false,message:'KYC request not found'});request.status='REJECTED';request.rejectedAt=new Date();request.rejectionReason=String(req.body.reason||'Documents could not be verified').slice(0,500);await request.save();await User.findByIdAndUpdate(request.user,{kycStatus:'REJECTED'});res.json({status:true,message:'KYC rejected'});}catch(e){next(e)}});

router.get('/settings',async(_req,res,next)=>{try{const settings=await GatewaySettings.findOneAndUpdate({key:'global'},{},{upsert:true,new:true,setDefaultsOnInsert:true});res.json({status:true,settings:safeSettings(settings)});}catch(e){next(e)}});
router.put('/settings',async(req,res,next)=>{try{const allowed=['gatewayName','supportContact','maintenanceMode','logoUrl','publicApiBaseUrl','webhookBaseUrl','settlementUpiId','settlementName','subscriptionUpiId','subscriptionUpiName','subscriptionPaymentLink','kycRequired','kycFee','kycUpiId','kycUpiName','showPanField','showAadhaarField','defaultTransactionFeePercent','paymentExpiryMinutes','minimumPaymentAmount','maximumPaymentAmount','gmailPaymentVerificationEnabled','gmailAutoSync','gmailSearchQuery','paymentVerificationMode','feeSettlementMode','googleOAuthEnabled','googleClientId','googleRedirectUri'];const patch=Object.fromEntries(allowed.filter(k=>k in req.body).map(k=>[k,req.body[k]]));if('googleClientSecret'in req.body){const secret=String(req.body.googleClientSecret||'');if(secret)patch.googleClientSecretEncrypted=encryptSecret(secret);}const settings=await GatewaySettings.findOneAndUpdate({key:'global'},patch,{upsert:true,new:true,setDefaultsOnInsert:true,runValidators:true});res.json({status:true,settings:safeSettings(settings)});}catch(e){next(e)}});
router.get('/gmail/connections',async(_req,res,next)=>{try{res.json({status:true,connections:await GmailConnection.find().select('owner email active lastCheckedAt createdAt updatedAt').populate('owner','name email userId').sort({updatedAt:-1}).lean()});}catch(e){next(e)}});

router.get('/admins',async(_req,res,next)=>{try{res.json({status:true,admins:await User.find({role:'admin'}).select('name email status createdAt updatedAt authProvider').sort({createdAt:1}).lean()});}catch(e){next(e)}});
router.post('/admins',async(req,res,next)=>{try{const name=String(req.body.name||'').trim(),email=String(req.body.email||'').trim().toLowerCase(),password=String(req.body.password||'');if(!name||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||password.length<8)return res.status(400).json({status:false,message:'Name, valid email and password of at least 8 characters are required'});const existing=await User.findOne({email}).select('+passwordHash');if(existing){if(existing.role!=='merchant')return res.status(409).json({status:false,message:'Email is already an administrator'});existing.role='admin';existing.status='active';existing.passwordHash=await bcrypt.hash(password,12);existing.trialStartedAt=null;existing.trialEndsAt=null;existing.plan=null;existing.planStartedAt=null;existing.planExpiresAt=null;existing.planStatus='NONE';existing.name=name;await existing.save({validateBeforeSave:false});return res.status(201).json({status:true,message:'Existing merchant promoted to admin',admin:{id:existing._id,name:existing.name,email:existing.email,role:existing.role,status:existing.status}});}const passwordHash=await bcrypt.hash(password,12);const admin=await User.create({name,email,passwordHash,authProvider:'password',role:'admin',status:'active',trialStartedAt:null,trialEndsAt:null,plan:null,planStatus:'NONE'});res.status(201).json({status:true,message:'Admin created successfully',admin:{id:admin._id,name:admin.name,email:admin.email,role:admin.role,status:admin.status}});}catch(e){next(e)}});
router.patch('/admins/:id',async(req,res,next)=>{try{const target=await User.findOne({_id:req.params.id,role:'admin'}).select('+passwordHash');if(!target)return res.status(404).json({status:false,message:'Admin not found'});if(target.email===envAdminEmail()&&req.body.status==='suspended')return res.status(400).json({status:false,message:'Bootstrap admin cannot be suspended'});if('status'in req.body){if(!['active','suspended'].includes(req.body.status))return res.status(400).json({status:false,message:'Invalid admin status'});target.status=req.body.status;}if(req.body.password){if(String(req.body.password).length<8)return res.status(400).json({status:false,message:'Password must be at least 8 characters'});target.passwordHash=await bcrypt.hash(String(req.body.password),12);}if(req.body.name)target.name=String(req.body.name).trim();target.trialStartedAt=null;target.trialEndsAt=null;target.plan=null;target.planStartedAt=null;target.planExpiresAt=null;target.planStatus='NONE';await target.save({validateBeforeSave:false});res.json({status:true,message:'Admin updated successfully',admin:{id:target._id,name:target.name,email:target.email,role:target.role,status:target.status}});}catch(e){next(e)}});

export default router;
