import { Router } from 'express';
import Merchant from '../models/Merchant.js';
import GmailConnection from '../models/GmailConnection.js';
import GatewaySettings from '../models/GatewaySettings.js';
import User from '../models/User.js';
import Order from '../models/Order.js';
import { requireAuth } from '../middleware/auth.js';
import { requireKycIfEnabled } from '../middleware/kyc.js';
import { verifyMerchantVerificationPayment, createVerificationOrder } from '../services/gmailImapPaymentVerifier.js';

const router = Router(); router.use(requireAuth, requireKycIfEnabled);
const normalizeUpi = value => String(value || '').trim().toLowerCase();
async function adminSettlementUpi(){const s=await GatewaySettings.findOne({key:'global'}).lean();return normalizeUpi(s?.settlementUpiId)}
async function isAdminUser(id){const u=await User.findById(id).select('role status').lean();return !!u&&u.role==='admin'&&u.status==='active'}
router.get('/',async(req,res,next)=>{try{res.json({status:true,merchants:await Merchant.find({owner:req.auth.sub,provider:{$ne:'admin_settlement'}}).sort({createdAt:-1})})}catch(e){next(e)}});
router.post('/',async(req,res,next)=>{try{const {name,provider,upiId,mobile,externalMerchantId,config}=req.body;if(!name||!provider)return res.status(400).json({status:false,message:'name and provider are required'});const admin=await isAdminUser(req.auth.sub),upi=normalizeUpi(upiId),adminUpi=await adminSettlementUpi();if(!admin&&String(provider).trim()==='admin_settlement')return res.status(403).json({status:false,message:'Admin Settlement UPI is reserved for the administrator.'});if(!admin&&upi&&adminUpi&&upi===adminUpi)return res.status(403).json({status:false,message:'This UPI ID is reserved for the administrator.'});const merchant=await Merchant.create({owner:req.auth.sub,name,provider,upiId:upi,mobile:String(mobile||'').replace(/\D/g,''),externalMerchantId,config,status:'pending',verificationStatus:'pending',verificationMessage:'Add Gmail address and Gmail App Password to verify this UPI.'});res.status(201).json({status:true,message:'Merchant added. Connect Gmail with an App Password and complete ₹1 verification.',merchant})}catch(e){next(e)}});
router.delete('/:merchantId',async(req,res,next)=>{try{const m=await Merchant.findOne({_id:req.params.merchantId,owner:req.auth.sub});if(!m)return res.status(404).json({status:false,message:'Merchant not found'});await GmailConnection.deleteOne({merchant:m._id});const admin=m.provider==='admin_settlement';await m.deleteOne();if(admin)await GatewaySettings.findOneAndUpdate({key:'global'},{$unset:{settlementUpiId:1,settlementName:1,settlementProvider:1,settlementMobile:1}});res.json({status:true,message:'Merchant and Gmail connection removed.'})}catch(e){next(e)}});
router.post('/:merchantId/verify',async(req,res,next)=>{try{const m=await Merchant.findOne({_id:req.params.merchantId,owner:req.auth.sub});if(!m)return res.status(404).json({status:false,message:'Merchant not found'});if(m.provider==='admin_settlement')return res.status(403).json({status:false,message:'Use the Admin Gmail connection screen for Admin Settlement.'});if(!m.upiId)return res.status(400).json({status:false,message:'Add the merchant UPI ID first.'});const order=await createVerificationOrder(m);res.json({status:true,verified:m.verificationStatus==='verified',message:m.verificationMessage,verificationOrder:order})}catch(e){next(e)}});
router.get('/:merchantId/verification',async(req,res,next)=>{try{let m=await Merchant.findOne({_id:req.params.merchantId,owner:req.auth.sub});if(!m)return res.status(404).json({status:false,message:'Merchant not found'});const gmail=await GmailConnection.findOne({merchant:m._id,active:true}).lean();if(String(req.query.check||'')==='1'&&gmail&&m.verificationStatus!=='verified'){const live=await Merchant.findById(m._id);const c=await GmailConnection.findOne({merchant:m._id,active:true}).select('+appPasswordEncrypted');if(live&&c){await verifyMerchantVerificationPayment({merchant:live,connection:c});m=await Merchant.findById(m._id)}}const order=m.config?.verificationOrderId?await Order.findOne({merchant:m._id,owner:req.auth.sub,orderId:String(m.config.verificationOrderId)}).select('orderId amount status paymentUrl expiresAt paidAt utr').lean():null;res.json({status:true,verificationStatus:m.verificationStatus,merchantStatus:m.status,verifiedAt:m.verifiedAt,verifiedEmail:m.verifiedEmail,message:m.verificationMessage,gmail:gmail?{email:gmail.email,connected:true,lastCheckedAt:gmail.lastCheckedAt}:{connected:false},verificationOrder:order})}catch(e){next(e)}});
router.get('/:merchantId/checkout',async(req,res,next)=>{try{const m=await Merchant.findOne({_id:req.params.merchantId,owner:req.auth.sub}).lean();if(!m)return res.status(404).json({status:false,message:'Merchant not found'});res.json({status:true,merchantId:m._id,checkout:m.config?.checkout||{}})}catch(e){next(e)}});
router.put('/:merchantId/checkout',async(req,res,next)=>{try{const m=await Merchant.findOne({_id:req.params.merchantId,owner:req.auth.sub});if(!m)return res.status(404).json({status:false,message:'Merchant not found'});const b=req.body||{};m.config={...(m.config||{}),checkout:{brandName:String(b.brandName||m.name).trim().slice(0,100),themeColor:/^#[0-9a-fA-F]{6}$/.test(String(b.themeColor||''))?String(b.themeColor):'#0B95BD',instructions:String(b.instructions||'').slice(0,3000),showQrCode:b.showQrCode!==false,showIntentButtons:b.showIntentButtons!==false,showUpiId:b.showUpiId!==false,showCopyButton:b.showCopyButton!==false,showBhim:b.showBhim!==false,brandLogo:typeof b.brandLogo==='string'&&b.brandLogo.length<=1500000?b.brandLogo:''}};await m.save();res.json({status:true,checkout:m.config.checkout})}catch(e){next(e)}});
export default router;
