import React, { useEffect, useState } from 'react';
import { ArrowLeft, CheckCircle2, KeyRound, Save, ShieldCheck, UserRound } from 'lucide-react';
import { api } from './api';
import './kyc.css';

export default function AccountPage(){
  const [data,setData]=useState(null); const [form,setForm]=useState({}); const [msg,setMsg]=useState(''); const [saving,setSaving]=useState(false);
  const load=async()=>{try{const d=await api('/account');setData(d);setForm({name:d.user?.name||'',mobile:d.user?.mobile||'',companyName:d.user?.companyName||'',panNumber:d.user?.panNumber||'',aadhaarNumber:d.user?.aadhaarNumber||'',location:d.user?.location||''});}catch(e){setMsg(e.message)}};
  useEffect(()=>{load()},[]);
  const save=async()=>{setSaving(true);setMsg('');try{await api('/account',{method:'PUT',body:JSON.stringify(form)});setMsg('Account settings saved successfully.')}catch(e){setMsg(e.message)}finally{setSaving(false)}};
  if(!data)return <div className="kyc-page"><div className="kyc-card">Loading account…</div></div>;
  const s=data.settings||{};
  return <div className="kyc-page"><div className="kyc-wrap"><button className="kyc-back" onClick={()=>{location.hash='dashboard'}}><ArrowLeft size={18}/> Dashboard</button><div className="kyc-hero"><div><span>ACCOUNT SETTING</span><h1>Personal Information</h1><p>Manage your merchant profile and KYC details.</p></div><div className="kyc-fee"><ShieldCheck size={31}/><small>{data.user?.kycStatus||'NOT_SUBMITTED'}</small></div></div>{msg&&<div className="kyc-message">{msg}</div>}<section className="kyc-section" style={{marginTop:16}}><div className="kyc-section-head"><UserRound/><h2>Personal Information</h2></div><Field label="Full Name" value={form.name} onChange={v=>setForm({...form,name:v})}/><Field label="Mobile Number" value={form.mobile} onChange={v=>setForm({...form,mobile:v.replace(/\D/g,'').slice(0,10)})}/><Field label="Company Name" value={form.companyName} onChange={v=>setForm({...form,companyName:v})}/><Field label="Location" value={form.location} onChange={v=>setForm({...form,location:v})}/>{s.showPanField&&<Field label="PAN Number" value={form.panNumber} onChange={v=>setForm({...form,panNumber:v.toUpperCase().slice(0,10)})}/>} {s.showAadhaarField&&<Field label="Aadhaar Number" value={form.aadhaarNumber} onChange={v=>setForm({...form,aadhaarNumber:v.replace(/\D/g,'').slice(0,12)})}/>}<button className="kyc-submit" onClick={save} disabled={saving}><Save size={18}/> {saving?'Saving…':'Save Changes'}</button></section><section className="kyc-section" style={{marginTop:16}}><div className="kyc-section-head"><KeyRound/><h2>KYC Verification</h2></div><Status status={data.user?.kycStatus}/>{s.kycRequired&&data.user?.kycStatus!=='VERIFIED'&&<button className="kyc-submit" onClick={()=>{location.hash='dashboard/kyc'}}>Start / Continue KYC · ₹{Number(s.kycFee||50).toLocaleString('en-IN')}</button>}{!s.kycRequired&&<div className="kyc-consent">KYC is currently optional. You can continue using the gateway without verification.</div>}</section></div></div>
}
function Field({label,value,onChange}){return <label className="kyc-field"><span>{label}</span><input value={value||''} onChange={e=>onChange(e.target.value)}/></label>}
function Status({status}){const map={VERIFIED:['Verified',CheckCircle2],PENDING_REVIEW:['Pending admin review',ShieldCheck],PENDING_PAYMENT:['Payment pending',KeyRound],REJECTED:['Rejected — resubmit documents',KeyRound],NOT_SUBMITTED:['Not submitted',KeyRound]};const [text,Icon]=map[status]||map.NOT_SUBMITTED;return <div style={{display:'flex',alignItems:'center',gap:10,padding:13,background:'#f4f6f9',borderRadius:11,marginBottom:14}}><Icon size={21}/><b>{text}</b></div>}
