import React, { useState } from 'react';
import { BookOpen, Copy, Link2, Search, ShieldCheck, Webhook, Zap } from 'lucide-react';
import './documentation.css';

// The documentation frontend currently lives on GitHub Pages.
export const DOCS_SITE_URL = 'https://omniupi.in/';
// API calls MUST point to the backend/API server, not the static GitHub Pages site.
export const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || 'https://api.omniupi.in';

const CREATE_ORDER_URL = `${API_BASE_URL}/api/create-order`;
const STATUS_URL = `${API_BASE_URL}/api/check-order-status`;

const createParams = [
  ['customer_mobile', 'string', 'Customer mobile number'],
  ['user_token', 'string', 'Unique API Token from your Account → API page'],
  ['amount', 'float', 'Payment amount in INR'],
  ['order_id', 'string', 'Unique order ID generated by your system'],
  ['redirect_url', 'url', 'Optional URL after successful payment'],
  ['remark1', 'string', 'Optional remark'],
  ['remark2', 'string', 'Optional remark'],
  ['merchant_id', 'string', 'Optional connected merchant ID when multiple merchants are connected'],
];

const phpCreate = `<?php
$api_url = '${CREATE_ORDER_URL}';

$post_data = [
    'customer_mobile' => '9999999999',
    'user_token'      => 'YOUR_API_TOKEN',
    'amount'          => '1.00',
    'order_id'        => 'ORDER123456',
    'redirect_url'    => 'https://example.com/success',
    'remark1'         => 'testremark',
    'remark2'         => 'testremark2',
];

$ch = curl_init($api_url);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_POST, true);
curl_setopt($ch, CURLOPT_POSTFIELDS, http_build_query($post_data));
curl_setopt($ch, CURLOPT_HTTPHEADER, ['Content-Type: application/x-www-form-urlencoded']);
$response = curl_exec($ch);
if (curl_errno($ch)) echo 'cURL Error: ' . curl_error($ch);
else echo $response;
curl_close($ch);
?>`;

const phpStatus = `<?php
$api_url = '${STATUS_URL}';
$post_data = [
    'user_token' => 'YOUR_API_TOKEN',
    'order_id'   => 'ORDER123456'
];
$ch = curl_init($api_url);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_POST, true);
curl_setopt($ch, CURLOPT_POSTFIELDS, http_build_query($post_data));
curl_setopt($ch, CURLOPT_HTTPHEADER, ['Content-Type: application/x-www-form-urlencoded']);
echo curl_exec($ch);
curl_close($ch);
?>`;

const phpWebhook = `<?php
if ($_SERVER['REQUEST_METHOD'] !== 'POST') { http_response_code(405); exit('Only POST requests are allowed'); }
$received_signature = $_SERVER['HTTP_X_WEBHOOK_SIGNATURE'] ?? '';
$instance_secret = 'YOUR_INSTANCE_SECRET';
$rawBody = file_get_contents('php://input');
$generated_signature = hash_hmac('sha256', $rawBody, $instance_secret);
if (!hash_equals($generated_signature, $received_signature)) { http_response_code(401); exit('Invalid Signature'); }
$data = json_decode($rawBody, true);
// Process SUCCESS only after signature verification.
$order_id = $data['order_id'] ?? '';
$amount = $data['amount'] ?? '';
$utr = $data['utr'] ?? '';
// Save/update your order in your database here.
echo 'SUCCESS';
?>`;

function CodeBlock({ code }) {
  const [copied, setCopied] = useState(false);
  const copy = async () => { try { await navigator.clipboard.writeText(code); setCopied(true); setTimeout(() => setCopied(false), 1400); } catch {} };
  return <div className="docs-code-wrap"><button className="docs-copy" onClick={copy}><Copy size={15}/> {copied ? 'Copied' : 'Copy'}</button><pre><code>{code}</code></pre></div>;
}

function ParamsTable({ rows }) {
  return <div className="docs-table-scroll"><table className="docs-table"><thead><tr><th>PARAMETER</th><th>TYPE</th><th>DESCRIPTION</th></tr></thead><tbody>{rows.map(([a,b,c]) => <tr key={a}><td><b>{a}</b></td><td>{b}</td><td>{c}</td></tr>)}</tbody></table></div>;
}

function SectionTitle({ icon: Icon, children }) { return <h2 className="docs-section-title"><span><Icon size={21}/></span>{children}</h2>; }
function ResponseBox({ children }) { return <div className="docs-response"><pre><code>{children}</code></pre></div>; }

export default function Documentation() {
  const [query, setQuery] = useState('');
  const filtered = createParams.filter(row => row.join(' ').toLowerCase().includes(query.trim().toLowerCase()));

  return <div className="documentation-page">
    <header className="docs-topbar"><button className="docs-back" onClick={() => { location.hash = 'dashboard'; }}>ϟ OmniUPI</button><div className="docs-top-title">Documentation</div><div className="docs-version">v3.0</div></header>
    <main className="docs-main">
      <div className="docs-hero"><div><span className="docs-eyebrow">DEVELOPER DOCUMENTATION</span><h1><BookOpen size={28}/> API Gateway Docs</h1><p>Create PayIN orders, open the payment page, check status and receive signed payment webhooks.</p></div><a href={DOCS_SITE_URL} target="_blank" rel="noreferrer" className="docs-site-link"><Link2 size={17}/> Docs Site</a></div>

      <div className="docs-notice"><ShieldCheck size={20}/><div><b>Important URL distinction</b><span>Documentation is hosted at <code>{DOCS_SITE_URL}</code>. API requests go to the backend at <code>{API_BASE_URL}</code>. When the backend/custom domain changes, update <code>VITE_API_BASE_URL</code>—do not point API calls to GitHub Pages.</span></div></div>

      <section className="docs-card"><SectionTitle icon={BookOpen}>Overview</SectionTitle><p>Every merchant gets a unique API Token and Instance Secret. Your bot/site/panel sends the API Token with an order request. The gateway creates the order against that merchant's connected UPI account. After Gmail verification confirms the matching order ID and amount, the order becomes <b>SUCCESS</b> and a signed webhook is sent to the merchant.</p></section>

      <section className="docs-card"><SectionTitle icon={Link2}>Endpoint PayIN API</SectionTitle><div className="endpoint"><b>POST</b><code>{CREATE_ORDER_URL}</code></div><div className="docs-search"><Search size={18}/><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search request parameters..."/></div><h3>Request Parameters</h3><ParamsTable rows={filtered}/><div className="docs-tip"><Zap size={18}/><span><b>Authentication:</b> send <code>user_token</code> or use <code>Authorization: Bearer YOUR_API_TOKEN</code>. Never expose the token or Instance Secret in browser/client-side code.</span></div></section>

      <section className="docs-card"><SectionTitle icon={Zap}>Example - Create PayIN Request</SectionTitle><h3>Request:</h3><CodeBlock code={phpCreate}/><h3>Response (Success):</h3><ResponseBox>{`{
  "status": true,
  "message": "Order Created Successfully",
  "result": {
    "txnStatus": "PENDING",
    "orderId": "ORDER123456",
    "amount": "1.00",
    "payment_url": "https://api.omniupi.in/api/payment/ORDER123456",
    "upi_url": "upi://pay?..."
  }
}`}</ResponseBox></section>

      <section className="docs-card"><SectionTitle icon={Search}>Endpoint for PayIN Status</SectionTitle><div className="endpoint"><b>POST</b><code>{STATUS_URL}</code></div><h3>Parameters</h3><ParamsTable rows={[[ 'user_token', 'string', 'Your API Token' ], [ 'order_id', 'string', 'The same order ID used during creation' ]]}/><h3>Example</h3><CodeBlock code={phpStatus}/><h3>Response</h3><ResponseBox>{`{
  "status": true,
  "message": "Transaction Successfully",
  "result": {
    "txnStatus": "SUCCESS",
    "orderId": "ORDER123456",
    "amount": "1.00",
    "date": "2026-08-17T12:00:00.000Z",
    "utr": "123456789012"
  }
}`}</ResponseBox></section>

      <section className="docs-card"><SectionTitle icon={Webhook}>Webhook</SectionTitle><p>Configure your webhook URL in the merchant API page. On verified payment the gateway sends a POST request with JSON and an HMAC-SHA256 signature.</p><ParamsTable rows={[[ 'Content-Type', 'header', 'application/json' ], [ 'X-Webhook-Signature', 'header', 'HMAC-SHA256(raw JSON, Instance Secret)' ], [ 'X-Webhook-Event', 'header', 'payment.success' ]]}/><h3>Webhook JSON</h3><ResponseBox>{`{
  "status": "SUCCESS",
  "order_id": "ORDER123456",
  "customer_mobile": "9999999999",
  "amount": "1.00",
  "utr": "123456789012",
  "remark1": "testremark",
  "remark2": "testremark2",
  "timestamp": 1786013741
}`}</ResponseBox><h3>PHP Webhook Handler</h3><CodeBlock code={phpWebhook}/><div className="docs-signature"><ShieldCheck size={22}/><div><b>Signature Verification</b><p>Calculate HMAC-SHA256 using the exact raw request body and your private Instance Secret. Compare it with <code>X-Webhook-Signature</code> before changing the order status.</p></div></div></section>

      <section className="docs-card docs-footer-card"><ShieldCheck size={20}/><div><b>Security</b><p>API Token identifies the merchant. Instance Secret signs webhooks. Regenerating either credential immediately invalidates the old credential.</p></div></section>
    </main>
  </div>;
}
