import React, { useState } from 'react';
import { ArrowLeft, ChevronDown, Code2, CreditCard, KeyRound, LifeBuoy, ShieldCheck, WalletCards, Webhook } from 'lucide-react';
import './faq.css';

const FAQS = [
  { q:'What is OmniUPI?', a:'OmniUPI is a UPI payment gateway platform that provides merchants with API-based payment order creation, hosted payment checkout, transaction status verification and webhook-based payment notifications.' },
  { q:'How does the payment flow work?', a:'Your application creates an order through the OmniUPI API. The API returns a payment URL. Your customer completes the payment on the hosted checkout, and your application can receive the resulting transaction status through the status API and configured webhook.' },
  { q:'Where can I find my API credentials?', a:'After your merchant account is ready, open Developer Setting → API Details in the dashboard. Keep the API key private and use it only from your server-side integration.' },
  { q:'Can I use the API in my website, bot or panel?', a:'Yes. The API is designed for server-side integrations, so it can be connected to a website backend, Telegram bot backend, SaaS panel, custom application or other software that can make HTTPS POST requests.' },
  { q:'What information is required to create an order?', a:'The PayIN create-order API accepts customer_mobile, user_token, amount, order_id, redirect_url, remark1 and remark2. The exact parameter names and request format are available in the API Documentation.' },
  { q:'How do I verify whether a customer has paid?', a:'Use the PayIN status endpoint with your API credential and order_id. For real-time server-to-server notifications, configure the webhook endpoint and verify the X-Webhook-Signature before updating your own order as paid.' },
  { q:'What is a webhook?', a:'A webhook is a server-to-server notification sent after a payment event. Your endpoint receives JSON containing the order and transaction information. Always validate the HMAC-SHA256 signature before processing the payment.' },
  { q:'What should I use as order_id?', a:'Use a unique order ID generated by your own system for every payment request. Never reuse an order ID for a different payment, because it can make reconciliation and status tracking unreliable.' },
  { q:'What happens after a successful payment?', a:'The transaction can be marked SUCCESS by the gateway and the response/webhook can contain details such as order ID, amount, transaction time and UTR when available. Your application should update its own order only after validating the gateway response or webhook.' },
  { q:'Can I change my API key?', a:'API credentials should be treated as secrets. If a credential is exposed or compromised, use the dashboard credential regeneration option when available and immediately update your server integration.' },
  { q:'Can I change the domain later?', a:'Yes. The current documentation and public API base URL can use the temporary GitHub Pages address while the platform is being prepared. When your custom domain is ready, the public URL can be migrated without changing the overall API integration design.' },
  { q:'What should I do if payment status is not updating?', a:'First check the order ID, API credential, server logs and status endpoint response. Then verify that your webhook URL is publicly reachable and that your webhook handler accepts POST requests and validates the signature correctly. If the issue continues, create a Support Ticket from the dashboard with the order ID and relevant error message.' },
  { q:'Is my API key safe to put in frontend JavaScript?', a:'No. Do not expose API credentials in browser JavaScript, mobile app source, public GitHub repositories or client-side HTML. Keep the credential on your backend and let your frontend communicate with your own server.' },
  { q:'Can I see all my transactions from the dashboard?', a:'Yes. The Transactions section is intended for viewing and managing your payment activity, including order information and transaction status.' },
  { q:'How can I contact support?', a:'Use Developer Setting → Support Ticket. You can create a ticket, select a category and priority, and continue the conversation with the support team from the ticket thread.' },
  { q:'What is required before going live?', a:'Complete your merchant/account setup, keep an active subscription if required by your plan, configure your API integration and webhook, test order creation and status verification, and confirm that your production server handles successful, failed and pending responses correctly.' },
];

export default function FaqPage(){
  const [open,setOpen]=useState(0);
  const groups=[
    {title:'About OmniUPI',icon:WalletCards,items:[0,1,14]},
    {title:'API & Integration',icon:Code2,items:[2,3,4,7,9,12]},
    {title:'Payments & Verification',icon:CreditCard,items:[5,6,8,11]},
    {title:'Account & Support',icon:ShieldCheck,items:[10,13,15]},
  ];
  return <div className="faq-page"><div className="faq-wrap">
    <header className="faq-header"><button className="faq-back" onClick={()=>{window.location.hash='dashboard'}}><ArrowLeft size={18}/> Dashboard</button><div className="faq-brand"><span>ϟ</span> OmniUPI</div></header>
    <section className="faq-hero"><div className="faq-badge"><LifeBuoy size={16}/> MERCHANT HELP CENTER</div><h1>Frequently Asked Questions</h1><p>OmniUPI, API integration, payment verification, webhooks, security and merchant support — all in one place.</p></section>
    <div className="faq-note"><Webhook size={21}/><div><b>Integration tip</b><span>Keep your API key on the server and verify the webhook signature before marking an order as paid.</span></div></div>
    {groups.map(group=>{const Icon=group.icon;return <section className="faq-group" key={group.title}><div className="faq-group-title"><Icon size={20}/><h2>{group.title}</h2></div>{group.items.map(i=>{const item=FAQS[i],isOpen=open===i;return <article className={'faq-item '+(isOpen?'open':'')} key={i}><button onClick={()=>setOpen(isOpen?-1:i)}><span>{item.q}</span><ChevronDown size={20}/></button>{isOpen&&<div className="faq-answer">{item.a}</div>}</article>})}</section>})}
    <div className="faq-footer-card"><KeyRound size={25}/><div><h3>Need help with a specific order?</h3><p>Create a Support Ticket and include your order ID, API response/error and approximate payment time. Never share your API secret or password in the ticket.</p></div><button onClick={()=>{window.location.hash='dashboard/support'}}>Open Support</button></div>
  </div></div>;
}
