import React,{useEffect,useState} from 'react';
import {ArrowLeft,Check,Eye,EyeOff,Mail,Plus,RefreshCw,ShieldCheck,Trash2,X,Zap} from 'lucide-react';
import {api} from './api';

const TYPES=['Paytm Business','BharatPe Merchant','Google Pay Business','PhonePe Business','FamPay wallet','Slice BANK','Digikhata','NetBanking - Direct UPI ID','UPI - Direct UPI ID'];
const back=()=>{window.location.hash='dashboard'};

export default function GmailConnectMerchant(){
 const [merchants,setMerchants]=useState([]),[type,setType]=useState(''),[label,setLabel]=useState(''),[mobile,setMobile]=useState(''),[upi,setUpi]=useState('');
 const [selected,setSelected]=useState(null),[email,setEmail]=useState(''),[appPassword,setAppPassword]=useState(''),[show,setShow]=useState(false),[step,setStep]=useState('form'),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[order,setOrder]=useState(null),[status,setStatus]=useState(null);
 const load=async()=>{try{const d=await api('/merchants');setMerchants(d.merchants||[])}catch(e){setError(e.message)}};
 useEffect(()=>{load()},[]);
 const add=async()=>{setError('');setMessage('');if(!type||!label||!/^[0-9]{10}$/.test(mobile)||!upi.trim())return setError('Merchant type, label, 10-digit mobile and UPI ID are required.');setBusy(true);try{const d=await api('/merchants',{method:'POST',body:JSON.stringify({name:label,provider:type,upiId:upi.trim(),mobile})});setMerchants(p=>[d.merchant,...p]);setSelected(d.merchant);setStep('form');setMessage('Merchant added. Now connect Gmail.');setType('');setLabel('');setMobile('');setUpi('')}catch(e){setError(e.message)}finally{setBusy(false)}};
 const test=async()=>{setError('');setMessage('');if(!email||!appPassword)return setError('Enter Gmail address and App Password.');setBusy(true);try{const d=await api('/gmail/test',{method:'POST',body:JSON.stringify({email,appPassword})});setMessage(`Gmail connected successfully. ${d.folders} mail folders detected.`);setStep('verified-gmail')}catch(e){setError(e.message)}finally{setBusy(false)}};
 const connect=async()=>{setError('');setMessage('');setBusy(true);try{const d=await api('/gmail/connect-merchant',{method:'POST',body:JSON.stringify({merchantId:selected._id,email,appPassword})});setOrder(d.verificationOrder);setMessage(d.message);setStep('payment');await load()}catch(e){setError(e.message)}finally{setBusy(false)}};
 const check=async()=>{setError('');setBusy(true);try{const d=await api(`/gmail/check/${selected._id}`,{method:'POST'});setOrder(d.order||d.verificationOrder||order);setMessage(d.message||'Payment not found yet.');if(d.verified){setStep('done');setStatus('verified');await load()}else setStep('payment')}catch(e){setError(e.message)}finally{setBusy(false)}};
 const select=async m=>{setSelected(m);setError('');setMessage('');setStep('form');try{const d=await api(`/gmail/status/${m._id}`);setStatus(d.merchant?.verificationStatus||m.verificationStatus);setOrder(d.verificationOrder);if(d.gmail?.connected){setEmail(d.gmail.email);if(d.verificationOrder)setStep(d.merchant?.verificationStatus==='verified'?'done':'payment')}}catch{}};
 const remove=async id=>{if(!confirm('Remove this merchant and its Gmail connection?'))return;try{await api(`/merchants/${id}`,{method:'DELETE'});setSelected(null);await load()}catch(e){setError(e.message)}};
 return <div style={{minHeight:'100vh',background:'#f5f7fb',fontFamily:'Inter,system-ui,sans-serif',color:'#253047'}}>
  <header style={{height:70,background:'#fff',borderBottom:'1px solid #e7ebf1',display:'flex',alignItems:'center',padding:'0 20px',gap:15}}><button onClick={back} style={iconBtn}><ArrowLeft size={19}/></button><div><b style={{fontSize:19}}>Connect Merchant</b><small style={{display:'block',color:'#8a94a5'}}>Gmail App Password verification</small></div></header>
  <main style={{maxWidth:1080,margin:'auto',padding:'24px 16px 50px'}}>
   {error&&<Alert text={error} type="error"/>}{message&&<Alert text={message} type="ok"/>}
   <section style={card}><div style={head}><div><h2 style={h2}>Add New Merchant</h2><p style={sub}>UPI account verification is now done through Gmail IMAP + App Password.</p></div><ShieldCheck size={25}/></div><div style={grid}><Field label="Merchant Type"><select value={type} onChange={e=>setType(e.target.value)} style={input}><option value="">Select Merchant</option>{TYPES.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Label"><input value={label} onChange={e=>setLabel(e.target.value)} placeholder="My Merchant" style={input}/></Field><Field label="10-digit Mobile"><input value={mobile} onChange={e=>setMobile(e.target.value.replace(/\D/g,'').slice(0,10))} placeholder="9876543210" style={input}/></Field><Field label="Merchant UPI ID"><input value={upi} onChange={e=>setUpi(e.target.value)} placeholder="merchant@upi" style={input}/></Field></div><button onClick={add} disabled={busy} style={primary}><Plus size={18}/> Add Merchant</button></section>
   <section style={card}><div style={head}><div><h2 style={h2}>My Merchants</h2><p style={sub}>Select a merchant to connect Gmail and verify it.</p></div><button onClick={load} style={iconBtn}><RefreshCw size={18}/></button></div>{!merchants.length?<div style={empty}>No merchants added yet.</div>:merchants.map(m=><div key={m._id} style={row}><div><b>{m.name}</b><small style={muted}>{m.provider} • {m.upiId||'No UPI ID'}</small></div><div style={{display:'flex',gap:8,alignItems:'center'}}><span style={m.verificationStatus==='verified'?okBadge:pendingBadge}>{m.verificationStatus==='verified'?'VERIFIED':'PENDING'}</span><button style={smallBtn} onClick={()=>select(m)}>Connect / Check</button><button style={dangerBtn} onClick={()=>remove(m._id)}><Trash2 size={15}/></button></div></div>)}</section>
   {selected&&<section style={card}><div style={head}><div><h2 style={h2}>{selected.name}</h2><p style={sub}>UPI: <b>{selected.upiId}</b></p></div><button onClick={()=>setSelected(null)} style={iconBtn}><X size={18}/></button></div>
    {step!=='done'&&<div style={steps}><span className={step==='form'?'activeStep':''}>1 Gmail</span><span className={step==='payment'?'activeStep':''}>2 ₹1 Verification</span><span className={step==='done'?'activeStep':''}>3 Verified</span></div>}
    {step==='form'&&<div style={grid}><Field label="Gmail Address"><div style={{position:'relative'}}><Mail size={18} style={mailIcon}/><input value={email} onChange={e=>setEmail(e.target.value)} type="email" placeholder="yourname@gmail.com" style={{...input,paddingLeft:42}}/></div></Field><Field label="Gmail App Password"><div style={{display:'flex',gap:8}}><input value={appPassword} onChange={e=>setAppPassword(e.target.value)} type={show?'text':'password'} placeholder="16-character App Password" style={input}/><button onClick={()=>setShow(!show)} style={iconBtn}>{show?<EyeOff size={18}/>:<Eye size={18}/>}</button></div><small style={help}>Use Gmail App Password, not your normal Gmail password.</small></Field><div style={{gridColumn:'1/-1'}}><button onClick={test} disabled={busy} style={secondary}><Mail size={18}/>{busy?'Testing…':'Test Gmail Connection'}</button></div></div>}
    {step==='verified-gmail'&&<div style={successBox}><Check size={25}/><div><b>Gmail connection verified</b><p>Now save this connection to the merchant.</p></div><button onClick={connect} disabled={busy} style={primary}>{busy?'Saving…':'Connect Gmail & Create ₹1 Verification'}</button></div>}
    {step==='payment'&&<div><div style={orderBox}><span>VERIFICATION PAYMENT</span><strong>₹{order?.amount||1}</strong><p>Pay exactly ₹1 to this merchant UPI using the order below.</p><code>{order?.orderId||'Loading…'}</code><small>Purpose / Remark: <b>{order?.orderId||'—'}</b></small></div><div style={{display:'flex',gap:10,marginTop:15,flexWrap:'wrap'}}><button onClick={()=>window.open(order?.paymentUrl,'_blank')} style={secondary}>Open ₹1 Payment</button><button onClick={check} disabled={busy} style={primary}><RefreshCw size={17}/>{busy?'Checking Gmail…':'Check Payment'}</button></div></div>}
    {step==='done'&&<div style={successBox}><div style={verifiedCircle}><Check size={30}/></div><div><h2 style={{margin:'0 0 5px'}}>UPI Verified Successfully</h2><p style={{margin:0,color:'#718096'}}>Gmail: {email}</p><small>Payment was matched using the exact Order ID and amount.</small></div></div>}
   </section>}
  </main>
 </div>
}
function Field({label,children}){return <label style={{display:'grid',gap:7,fontSize:13,fontWeight:800,color:'#3a4659'}}>{label}{children}</label>}
function Alert({text,type}){return <div style={{padding:13,borderRadius:12,marginBottom:14,background:type==='error'?'#fff1f2':'#ecfdf5',color:type==='error'?'#be123c':'#047857',border:`1px solid ${type==='error'?'#fecdd3':'#a7f3d0'}`}}>{text}</div>}
const card={background:'#fff',border:'1px solid #e7ebf1',borderRadius:18,padding:20,marginBottom:18,boxShadow:'0 8px 25px rgba(31,41,55,.05)'};const head={display:'flex',justifyContent:'space-between',alignItems:'center',gap:10,borderBottom:'1px solid #edf0f4',paddingBottom:14,marginBottom:18};const h2={margin:0,fontSize:21};const sub={margin:'5px 0 0',color:'#7d8797',fontSize:13};const grid={display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:15};const input={width:'100%',boxSizing:'border-box',padding:'13px',border:'1px solid #dfe4eb',borderRadius:11,fontSize:15,outline:0,background:'#fff'};const primary={border:0,borderRadius:11,padding:'12px 17px',background:'linear-gradient(135deg,#6269e8,#19b99a)',color:'#fff',fontWeight:850,display:'inline-flex',alignItems:'center',gap:8,cursor:'pointer',marginTop:16};const secondary={border:'1px solid #dce2eb',borderRadius:11,padding:'11px 15px',background:'#fff',color:'#4e5ed0',fontWeight:800,display:'inline-flex',alignItems:'center',gap:8};const iconBtn={border:'1px solid #e0e5ec',background:'#fff',borderRadius:10,width:40,height:40,display:'grid',placeItems:'center',color:'#5965c9'};const row={display:'flex',justifyContent:'space-between',alignItems:'center',gap:12,padding:'14px 0',borderBottom:'1px solid #edf0f4'};const muted={display:'block',fontSize:12,color:'#8791a1',marginTop:4};const smallBtn={border:'1px solid #dce2eb',background:'#fff',borderRadius:9,padding:'8px 10px',fontWeight:750,color:'#5965c9'};const dangerBtn={...iconBtn,width:34,height:34,color:'#c2415c'};const okBadge={padding:'6px 9px',borderRadius:99,fontSize:10,fontWeight:900,background:'#dcfce7',color:'#15803d'};const pendingBadge={padding:'6px 9px',borderRadius:99,fontSize:10,fontWeight:900,background:'#fef3c7',color:'#a16207'};const empty={padding:35,textAlign:'center',color:'#8a94a4'};const steps={display:'flex',gap:8,marginBottom:20,flexWrap:'wrap'};const activeStep={background:'#e8eaff',color:'#4f5dcc',padding:'7px 11px',borderRadius:99,fontWeight:800,fontSize:12};const mailIcon={position:'absolute',left:13,top:13,color:'#7b8798'};const help={color:'#8a94a4',fontWeight:500};const successBox={display:'flex',alignItems:'center',gap:15,padding:18,borderRadius:15,background:'#ecfdf5',border:'1px solid #a7f3d0',color:'#047857'};const orderBox={textAlign:'center',padding:24,borderRadius:18,background:'linear-gradient(145deg,#f4f5ff,#edfffa)',border:'1px solid #e2e7f0'};const verifiedCircle={width:58,height:58,borderRadius:'50%',display:'grid',placeItems:'center',background:'#10b981',color:'#fff'};
