import React, { useEffect, useState } from 'react';
import { ArrowLeft, CheckCircle2, Clock3, CreditCard, FileCheck2, ShieldCheck, Upload, XCircle } from 'lucide-react';
import { api } from './api';
import './kyc.css';

const empty = { aadhaarNumber: '', aadhaarName: '', aadhaarFront: '', aadhaarBack: '', panNumber: '', panName: '', panFront: '', panBack: '' };

export default function KycPage() {
  const [config, setConfig] = useState(null); const [form, setForm] = useState(empty); const [latest, setLatest] = useState(null); const [status, setStatus] = useState('NOT_SUBMITTED'); const [busy, setBusy] = useState(false); const [payment, setPayment] = useState(null); const [message, setMessage] = useState(''); const [verifiedPopup, setVerifiedPopup] = useState(false);
  const load = async () => { try { const [c, m] = await Promise.all([api('/kyc/config'), api('/kyc/me')]); setConfig(c); setLatest(m.latest); setStatus(m.kycStatus); if (m.kycStatus === 'VERIFIED') setVerifiedPopup(true); } catch (e) { setMessage(e.message); } };
  useEffect(() => { load(); }, []);
  useEffect(() => { const orderId = payment?.orderId || (status === 'PENDING_REVIEW' ? latest?.orderId : null); if (!orderId) return; const id = setInterval(async () => { try { const d = await api(`/kyc/order/${encodeURIComponent(orderId)}`); setLatest(d.order); if (d.order.status === 'SUBMITTED') { setStatus('PENDING_REVIEW'); setPayment(null); setMessage('Payment successful. Your KYC request has been sent to admin for review.'); } else if (d.order.status === 'VERIFIED') { setStatus('VERIFIED'); setPayment(null); setVerifiedPopup(true); clearInterval(id); } else if (d.order.status === 'REJECTED') { setStatus('REJECTED'); setPayment(null); setMessage(d.order.rejectionReason || 'KYC request was rejected.'); clearInterval(id); } } catch {} }, 5000); return () => clearInterval(id); }, [payment?.orderId, status, latest?.orderId]);
  const file = (key, f) => { if (!f) return; if (f.size > 2_200_000) { setMessage('Please use an image below 2.2MB.'); return; } const reader = new FileReader(); reader.onload = () => setForm(v => ({ ...v, [key]: reader.result })); reader.readAsDataURL(f); };
  const submit = async e => { e.preventDefault(); setBusy(true); setMessage(''); try { const d = await api('/kyc/start', { method: 'POST', body: JSON.stringify(form) }); setPayment(d.request); setStatus('PENDING_PAYMENT'); setMessage('KYC form saved. Complete the payment to submit your request.'); } catch (e) { setMessage(e.message); } finally { setBusy(false); } };
  if (!config) return <div className="kyc-page"><div className="kyc-card">Loading KYC settings…</div></div>;
  if (!config.enabled) return <div className="kyc-page"><div className="kyc-card"><ShieldCheck size={45}/><h1>KYC Not Required</h1><p>Administrator has currently disabled mandatory KYC.</p></div></div>;
  const showForm = status !== 'VERIFIED' && status !== 'PENDING_REVIEW';
  return <div className="kyc-page"><div className="kyc-wrap"><button className="kyc-back" onClick={() => { location.hash = 'dashboard/account'; }}><ArrowLeft size={18}/> Account Settings</button><div className="kyc-hero"><div><span>KYC VERIFICATION</span><h1>Verify Your Identity</h1><p>Submit Aadhaar and PAN documents. After payment, your request goes to the administrator for manual verification.</p></div><div className="kyc-fee"><b>₹{Number(config.fee).toLocaleString('en-IN')}</b><small>KYC fee</small></div></div>{message && <div className="kyc-message">{message}</div>}{status === 'VERIFIED' ? <div className="kyc-status success"><CheckCircle2 size={44}/><h2>Your KYC is Verified</h2><p>Your KYC has been successfully verified.</p></div> : status === 'PENDING_REVIEW' ? <div className="kyc-status"><Clock3 size={44}/><h2>KYC Under Review</h2><p>Payment received. Your documents are now with the administrator for verification. This page will automatically show the verification popup when approved.</p></div> : <form className="kyc-form" onSubmit={submit}><DocSection title="Aadhaar Card" icon={<FileCheck2/>}><Field label="Aadhaar Number" value={form.aadhaarNumber} set={v=>setForm({...form,aadhaarNumber:v.replace(/\D/g,'').slice(0,12)})} placeholder="12-digit Aadhaar number"/><Field label="Name as per Aadhaar" value={form.aadhaarName} set={v=>setForm({...form,aadhaarName:v})} placeholder="Full name"/><ImageField label="Aadhaar Front" value={form.aadhaarFront} onChange={f=>f?file('aadhaarFront',f):setForm(v=>({...v,aadhaarFront:''}))}/><ImageField label="Aadhaar Back" value={form.aadhaarBack} onChange={f=>f?file('aadhaarBack',f):setForm(v=>({...v,aadhaarBack:''}))}/></DocSection><DocSection title="PAN Card" icon={<CreditCard/>}><Field label="PAN Number" value={form.panNumber} set={v=>setForm({...form,panNumber:v.toUpperCase().slice(0,10)})} placeholder="ABCDE1234F"/><Field label="Name as per PAN" value={form.panName} set={v=>setForm({...form,panName:v})} placeholder="Full name"/><ImageField label="PAN Front" value={form.panFront} onChange={f=>f?file('panFront',f):setForm(v=>({...v,panFront:''}))}/><ImageField label="PAN Back" value={form.panBack} onChange={f=>f?file('panBack',f):setForm(v=>({...v,panBack:''}))}/></DocSection><div className="kyc-consent">Documents are encrypted before storage and are visible only to administrators reviewing your KYC request.</div><button className="kyc-submit" disabled={busy}>{busy ? 'Preparing payment…' : <>Pay ₹{Number(config.fee).toLocaleString('en-IN')} & Submit KYC <span>→</span></>}</button></form>}{payment && <PaymentModal payment={payment} close={()=>setPayment(null)}/>} {verifiedPopup && <div className="kyc-popup"><div><CheckCircle2 size={58}/><h2>Your KYC Verified</h2><p>Your KYC has been successfully verified. You can now use the gateway.</p><button onClick={()=>setVerifiedPopup(false)}>Continue</button></div></div>}</div></div>;
}
function DocSection({title,icon,children}){return <section className="kyc-section"><div className="kyc-section-head">{icon}<h2>{title}</h2></div>{children}</section>}
function Field({label,value,set,placeholder}){return <label className="kyc-field"><span>{label}</span><input value={value} onChange={e=>set(e.target.value)} placeholder={placeholder} required/></label>}
function ImageField({label,value,onChange}){return <label className="kyc-image-field"><span>{label}</span>{value ? <div className="preview"><img src={value} alt="document preview"/><button type="button" onClick={()=>onChange(null)}><XCircle size={18}/></button></div> : <><Upload size={25}/><b>Upload / Camera</b><small>JPG, PNG or WebP · max 2.2MB</small><input type="file" accept="image/*" capture="environment" onChange={e=>onChange(e.target.files?.[0])}/></>}</label>}
function PaymentModal({payment,close}){return <div className="kyc-popup"><div><Clock3 size={50}/><h2>Complete KYC Payment</h2><p>Pay exactly ₹{Number(payment.amount).toLocaleString('en-IN')} to submit your KYC request.</p><div className="kyc-order">Order ID: <b>{payment.orderId}</b></div><a className="kyc-pay-btn" href={payment.paymentUrl}>Open UPI App</a><small>After payment, keep this screen open. Payment verification will automatically submit the request.</small><button className="kyc-close" onClick={close}>I'll pay later</button></div></div>}
