import React from 'react';
import {ArrowLeft,CheckCircle2,ChevronRight,ShieldCheck,FileText,Scale,RefreshCcw,Truck,Headphones} from 'lucide-react';

const EFFECTIVE='18 August 2026';

const content={
  privacy:{title:'Privacy Policy',kicker:'PRIVACY & DATA PROTECTION',icon:ShieldCheck,intro:'This Privacy Policy explains how OmniUPI collects, uses, stores and protects information when you use our website, merchant dashboard, payment-link features and related services.',sections:[
    ['1. Information We Collect','Depending on the feature you use, we may collect account information such as your name, email address, phone number, login details, merchant identifiers, UPI IDs, transaction or payment-link information, device/browser information, IP address, logs and support communications. We only request information that is reasonably relevant to providing, securing or improving the service.'],
    ['2. How We Use Information','We use information to create and manage accounts, provide merchant and payment-link functionality, authenticate users, process or facilitate configured payment workflows, prevent fraud and abuse, maintain security, provide support, troubleshoot issues, improve the platform and comply with applicable legal or regulatory obligations.'],
    ['3. Google User Data','When you use Google account authentication, OmniUPI may receive basic Google account information made available through the authentication flow, such as your name and email address. We use this information only to authenticate your account, create or access your OmniUPI merchant account, maintain account security and provide the OmniUPI services you request. We do not sell Google user data, use it for targeted advertising, use it for credit scoring or data brokerage, or use it to train generalized AI/ML models. We do not transfer Google user data to third parties except service providers or integrations reasonably necessary to authenticate, host, secure or operate the requested OmniUPI functionality, or when disclosure is required by law. Our handling of Google user data is limited to the purposes disclosed here and is intended to comply with Google API Services User Data Policy and its Limited Use requirements.'],
    ['4. Payment Information','OmniUPI should not be used to collect or store card PINs, UPI PINs, CVV values, passwords for banking applications or other authentication secrets. Where a third-party bank, payment service provider or merchant application handles payment authentication, that provider’s terms and privacy policy may also apply.'],
    ['5. Sharing & Service Providers','Information may be shared with vendors and service providers that help operate hosting, databases, analytics, authentication, communication, security or payment-related integrations, only to the extent reasonably necessary. We may also disclose information when required by law, court order, lawful government request, or to investigate fraud, security incidents or abuse.'],
    ['6. Security','We use reasonable technical and organisational safeguards appropriate to the nature of the information, including access controls, authentication, encrypted connections and logging where applicable. No internet service can guarantee absolute security, so users should also protect passwords, API credentials and devices.'],
    ['7. Retention','We retain information for as long as reasonably necessary for the purpose for which it was collected, account operation, security, dispute handling, backups, audits and applicable legal obligations. Retention periods may differ by data type and service.'],
    ['8. Your Choices','You may request access, correction or deletion of personal information where applicable, subject to legal, security, accounting and transaction-record requirements. You should contact us with enough information to verify the request.'],
    ['9. Cookies & Similar Technologies','The website may use essential cookies or local storage for login sessions, preferences, security and functionality. Optional analytics or similar technologies, if enabled, may be described in the relevant service interface.'],
    ['10. Children','Our merchant services are intended for businesses and users who are legally able to enter into applicable agreements. We do not knowingly seek personal information from children for independent use of the merchant platform.'],
    ['11. Changes','We may update this policy when our services, technology or legal obligations change. The updated version will be published on this page with a revised effective date.'],
  ]},
  terms:{title:'Terms & Conditions',kicker:'SERVICE TERMS',icon:Scale,intro:'These Terms & Conditions govern access to and use of the OmniUPI website, merchant platform, APIs, payment-link tools and related software services.',sections:[
    ['1. Acceptance','By creating an account or using OmniUPI, you agree to these Terms, the Privacy Policy and any service-specific terms shown during signup or purchase. If you use OmniUPI for a business, you confirm that you have authority to bind that business.'],
    ['2. Service Role','OmniUPI provides software and infrastructure features for merchant payment workflows. The exact role of OmniUPI, a merchant, bank, payment service provider, or other integration partner depends on the configured product and applicable arrangement. Nothing on this website should be read as a representation of regulatory authorization unless expressly stated and verifiable.'],
    ['3. Merchant Responsibilities','Merchants are responsible for providing accurate information, maintaining lawful products and services, complying with tax, consumer-protection, KYC/AML, payment-network and other applicable requirements, and obtaining all permissions or registrations required for their business. Merchants must not use the platform for unlawful, fraudulent, deceptive or prohibited activities.'],
    ['4. Account & Credentials','You are responsible for your account credentials, API keys, merchant credentials and activity performed through your account. Do not share secret keys or authentication credentials publicly. Notify us promptly if you suspect unauthorised access.'],
    ['5. Payments & Transactions','A payment request, payment-link creation or status shown by the platform does not by itself guarantee successful settlement. Transaction status may depend on banks, UPI participants, payment providers, network availability and reconciliation. Final settlement and refund obligations are subject to the applicable payment arrangement.'],
    ['6. Fees & Plans','Subscription fees, trial periods, limits and other commercial terms are those displayed or agreed for the applicable plan. We may change future pricing with reasonable notice. Taxes, bank charges or third-party charges may apply where relevant.'],
    ['7. Prohibited Use','You may not use OmniUPI to facilitate fraud, money laundering, unauthorised financial activity, impersonation, malware, illegal goods or services, deceptive schemes, abuse of payment systems, or any activity prohibited by applicable law or our risk controls.'],
    ['8. Availability','We aim to provide a reliable service but do not guarantee uninterrupted availability. Maintenance, third-party outages, banking/UPI downtime, internet failures, security incidents or events beyond our reasonable control may affect the service.'],
    ['9. Suspension & Termination','We may restrict, suspend or terminate access where reasonably necessary for security, suspected fraud or abuse, non-payment, legal compliance, breach of these Terms, or protection of users and payment partners. Where appropriate, we may request verification before restoring access.'],
    ['10. Intellectual Property','The OmniUPI software, branding, design, documentation and related materials are owned by or licensed to the service operator. You receive a limited, non-exclusive right to use the service according to these Terms and do not receive ownership of the underlying software.'],
    ['11. Liability','To the extent permitted by applicable law, OmniUPI is not responsible for losses caused by inaccurate merchant information, compromised credentials, third-party bank or payment-provider failures, unlawful merchant activity, or events outside our reasonable control. Nothing in these Terms excludes liability that cannot lawfully be excluded.'],
    ['12. Governing Law','These Terms are intended to be interpreted under applicable laws of India, subject to the rights and remedies available under mandatory law. Any dispute-resolution procedure applicable to a specific service or contract will take precedence where expressly agreed.'],
  ]},
  refund:{title:'Refund & Cancellation Policy',kicker:'REFUNDS & CANCELLATIONS',icon:RefreshCcw,intro:'This policy explains how cancellations, subscription refunds and payment-related disputes are handled for OmniUPI services.',sections:[
    ['1. Subscription Cancellation','You may request cancellation of a subscription according to the plan terms. Cancellation normally prevents future renewals but does not automatically create a refund for a period already used, except where required by law or expressly promised at purchase.'],
    ['2. Trial Period','If a free trial is offered, the trial duration and eligibility are shown during signup. Trial access may be limited, suspended or withdrawn where there is suspected abuse, duplicate accounts or security concerns.'],
    ['3. Refund Eligibility','Where a refund is available, eligibility may depend on duplicate charges, service unavailability attributable to OmniUPI, billing errors, or another circumstance expressly covered by the applicable commercial terms. Third-party payment processing charges may be non-refundable where lawfully permitted.'],
    ['4. Payment Failure','A failed, pending, reversed or rejected payment is not automatically a successful charge. If your bank or payment provider shows a debit while the merchant transaction remains unsuccessful, the customer should first follow the applicable bank/payment-provider dispute or reversal process; OmniUPI can assist with transaction references where available.'],
    ['5. Merchant Refunds','Refunds for goods or services sold by a merchant are generally the responsibility of the merchant unless a separate agreement states otherwise. OmniUPI does not decide the merchant’s underlying consumer refund obligation.'],
    ['6. How to Request a Refund','Include the account email, transaction/reference ID, amount, date and reason for the request. We may request additional information to verify the transaction and prevent fraudulent refund claims.'],
    ['7. Processing Time','Approved refunds are initiated through the relevant payment or billing channel. The time for funds to appear may depend on the bank, card network, UPI participant or payment provider.'],
  ]},
  shipping:{title:'Shipping & Delivery Policy',kicker:'DIGITAL SERVICES',icon:Truck,intro:'OmniUPI primarily provides digital software, merchant tools and online services. No physical shipment is normally required for these services.',sections:[
    ['1. Digital Delivery','After successful account creation or subscription activation, access to eligible digital features is provided electronically through the website, dashboard, API or other configured delivery channel.'],
    ['2. Activation','Activation may be immediate or may require account verification, payment confirmation, KYC or merchant approval depending on the service configuration.'],
    ['3. No Physical Shipping','Because the standard OmniUPI service is digital, there is normally no courier delivery, shipping fee or physical delivery address requirement. If a future product includes a physical item, its separate delivery terms will be shown at checkout.'],
    ['4. Service Delays','Third-party outages, verification queues, payment confirmation delays or maintenance may delay activation. We will take reasonable steps to restore or complete delivery of the digital service.'],
  ]},
  contact:{title:'Contact Us',kicker:'SUPPORT & GRIEVANCE',icon:Headphones,intro:'We want merchants and customers to have a clear way to raise questions, billing concerns, security issues and service complaints.',sections:[
    ['1. Support','For account, integration, billing or merchant-dashboard issues, use the Support Ticket feature available in the merchant dashboard where enabled.'],
    ['2. Payment Issues','For a payment-related complaint, include the transaction/reference ID, date, amount, merchant information and a short description. Never send your UPI PIN, password, OTP, CVV or other authentication secret.'],
    ['3. Security Reports','If you discover a security vulnerability or believe an account has been compromised, report it promptly through the available support channel and avoid publicly posting sensitive details.'],
    ['4. Information to Include','For faster assistance, provide the email used for the account, relevant reference IDs, screenshots where safe, and the exact error message.'],
    ['5. Response','We aim to review support requests within a reasonable period. Complex payment, bank, verification or third-party issues may require additional time because they depend on external systems.'],
  ]}
};

export default function LegalPage({type='privacy'}){
  const data=content[type]||content.privacy; const Icon=data.icon;
  return <div className="legal-page">
    <header className="legal-header"><button className="legal-brand" onClick={()=>{window.location.hash='';window.scrollTo(0,0)}}><span>ϟ</span> OmniUPI</button><button className="legal-back" onClick={()=>{window.location.hash='';window.scrollTo(0,0)}}><ArrowLeft size={17}/> Back to home</button></header>
    <main className="legal-main"><div className="legal-hero"><div className="legal-icon"><Icon size={30}/></div><div><span>{data.kicker}</span><h1>{data.title}</h1><p>{data.intro}</p></div></div><div className="legal-meta"><span><CheckCircle2 size={15}/> Effective {EFFECTIVE}</span><span>Last updated {EFFECTIVE}</span></div><article className="legal-card">{data.sections.map(([heading,text])=><section key={heading}><h2>{heading}</h2><p>{text}</p></section>)}<div className="legal-note"><FileText size={18}/><div><strong>Important</strong><p>This page is general website/service information and is not a substitute for legal advice. Your exact obligations may depend on your business model, contracts, payment partners and applicable law.</p></div></div></article><div className="legal-nav"><a href="#privacy">Privacy Policy <ChevronRight size={15}/></a><a href="#terms">Terms & Conditions <ChevronRight size={15}/></a><a href="#refund">Refund Policy <ChevronRight size={15}/></a><a href="#shipping">Shipping Policy <ChevronRight size={15}/></a><a href="#contact">Contact Us <ChevronRight size={15}/></a></div></main><footer className="legal-footer"><div><strong>OmniUPI</strong><span>Modern UPI payment infrastructure for businesses.</span></div><div className="legal-footer-links"><a href="#privacy">Privacy</a><a href="#terms">Terms</a><a href="#refund">Refunds</a><a href="#shipping">Shipping</a><a href="#contact">Contact</a></div><small>© 2026 OmniUPI. All rights reserved.</small></footer>
  </div>
}

export {content};
