import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import App from './App.jsx';
import GmailConnectMerchant from './GmailConnectMerchant.jsx';
import OAuthBridge from './OAuthBridge.jsx';
import LegalPage from './LegalPages.jsx';
import Transactions from './Transactions.jsx';
import {CheckoutPage,PaymentLinkPage,PublicPaymentPage} from './CheckoutRoutesV2.jsx';
import {PaymentLinkPageFixed,PublicPaymentPageFixed} from './PaymentLinkFixed.jsx';
import SubscriptionPage from './SubscriptionPage.jsx';
import AccountPage from './AccountPage.jsx';
import PasswordPage from './PasswordPage.jsx';
import KycPage from './KycPage.jsx';
import ApiPage from './ApiPage.jsx';
import MerchantApkPage from './MerchantApkPage.jsx';
import VideoMerchant from './VideoMerchant.jsx';
import Documentation from './Documentation.jsx';
import SupportTicketPage from './SupportTicketPage.jsx';
import FaqPage from './FaqPage.jsx';
import HomeLegalFooter from './HomeLegalFooter.jsx';
import {api} from './api';
import './styles.css';
import './dashboard.css';
import './kyc.css';
import './video-merchant.css';
import './payment-link-fix.css';
import './mobile-dashboard.css';

function Root(){const[hash,setHash]=useState(window.location.hash);useEffect(()=>{const onHashChange=()=>setHash(window.location.hash);window.addEventListener('hashchange',onHashChange);return()=>window.removeEventListener('hashchange',onHashChange)},[]);const legal={'#privacy':'privacy','#terms':'terms','#refund':'refund','#shipping':'shipping','#contact':'contact'};const legalPaths={'/privacy-policy.html':'privacy','/terms.html':'terms','/refund-policy.html':'refund','/shipping-policy.html':'shipping','/contact.html':'contact'};if(legal[hash])return <><OAuthBridge/><LegalPage type={legal[hash]}/></>;if(legalPaths[window.location.pathname])return <><OAuthBridge/><LegalPage type={legalPaths[window.location.pathname]}/></>;if(window.location.pathname==='/auth')return <><OAuthBridge/><SubscriptionPage/></>;if(hash==='#dashboard/connect')return <><OAuthBridge/><KycGate><GmailConnectMerchant/></KycGate></>;if(hash==='#dashboard/account')return <><OAuthBridge/><AccountPage/></>;if(hash==='#dashboard/password')return <><OAuthBridge/><PasswordPage/></>;if(hash==='#dashboard/kyc')return <><OAuthBridge/><KycPage/></>;if(hash==='#dashboard/api')return <><OAuthBridge/><ApiPage/></>;if(hash==='#dashboard/apk')return <><OAuthBridge/><MerchantApkPage/></>;if(hash==='#dashboard/video')return <><OAuthBridge/><KycGate><VideoMerchant/></KycGate></>;if(hash==='#dashboard/docs')return <><OAuthBridge/><KycGate><Documentation/></KycGate></>;if(hash==='#subscription'||hash==='#dashboard/subscription')return <><OAuthBridge/><KycGate><SubscriptionPage/></KycGate></>;if(hash==='#dashboard/transactions')return <><OAuthBridge/><KycGate><Transactions onBack={()=>{window.location.hash='dashboard'}}/></KycGate></>;if(hash==='#dashboard/checkout')return <><OAuthBridge/><KycGate><CheckoutPage/></KycGate></>;if(hash==='#dashboard/payment-link')return <><OAuthBridge/><KycGate><PaymentLinkPageFixed/></KycGate></>;if(hash.startsWith('#pay?'))return <><OAuthBridge/><PublicPaymentPageFixed route={hash}/></>;if(hash==='#dashboard'||hash.startsWith('#dashboard/'))return <><OAuthBridge/><KycGate><App/></KycGate></>;return <><OAuthBridge/><App/><HomeLegalFooter/></>}

function VerificationLoader(){return <div className="omni-verification-loader" role="status" aria-live="polite"><style>{`.omni-verification-loader{position:fixed;inset:0;z-index:999999;display:grid;place-items:center;padding:20px;background:linear-gradient(145deg,#f4f6ff,#ecfffa);font-family:Inter,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.ovl-backdrop{position:absolute;inset:0;background:radial-gradient(circle at 50% 35%,#ffffffd9,transparent 58%)}.ovl-card{position:relative;width:min(410px,100%);padding:34px 26px 28px;border:1px solid #ffffffcc;border-radius:28px;background:#fffffff2;box-shadow:0 30px 90px #17213a20;text-align:center;backdrop-filter:blur(18px);animation:ovlIn .35s ease-out}.ovl-logo{width:68px;height:68px;margin:0 auto 16px;border-radius:21px;display:grid;place-items:center;color:#fff;font-size:37px;font-weight:950;background:linear-gradient(135deg,#6269e8,#19b99a);box-shadow:0 14px 30px #6269e84d}.ovl-spinner{height:30px;display:flex;justify-content:center;align-items:center;gap:6px;margin:5px 0 17px}.ovl-spinner i{width:7px;height:7px;border-radius:50%;background:#6269e8;animation:ovlDot 1.1s infinite ease-in-out}.ovl-spinner i:nth-child(2){animation-delay:.15s}.ovl-spinner i:nth-child(3){animation-delay:.3s}.ovl-eyebrow{font-size:10px;letter-spacing:.16em;font-weight:900;color:#6269e8}.ovl-card h1{margin:8px 0 8px;font-size:23px;color:#172033}.ovl-card p{margin:0 auto 19px;max-width:330px;color:#758094;font-size:13px;line-height:1.65}.ovl-progress{height:5px;background:#e9edf5;border-radius:99px;overflow:hidden;margin:0 auto 11px;max-width:300px}.ovl-progress span{display:block;width:42%;height:100%;border-radius:99px;background:linear-gradient(90deg,#6269e8,#19b99a);animation:ovlProgress 1.7s infinite ease-in-out}.ovl-card small{color:#9aa3b1;font-size:10px}@keyframes ovlDot{0%,80%,100%{transform:scale(.65);opacity:.45}40%{transform:scale(1.15);opacity:1}}@keyframes ovlProgress{0%{transform:translateX(-130%)}100%{transform:translateX(320%)}}@keyframes ovlIn{from{opacity:0;transform:translateY(8px) scale(.98)}to{opacity:1;transform:none}}@media(max-width:480px){.ovl-card{padding:30px 20px 25px;border-radius:24px}.ovl-card h1{font-size:21px}}`}</style><div className="ovl-backdrop"/><div className="ovl-card"><div className="ovl-logo"><span>ϟ</span></div><div className="ovl-spinner"><i/><i/><i/></div><div className="ovl-eyebrow">OMNIUPI SECURITY</div><h1>Checking account verification</h1><p>We're securely checking your account status. Please wait a moment.</p><div className="ovl-progress"><span/></div><small>Secure connection · Account verification in progress</small></div></div>}
function KycGate({children}){const[state,setState]=useState('loading');const[approved,setApproved]=useState(false);const[wasBlocked,setWasBlocked]=useState(false);useEffect(()=>{let alive=true;const check=async()=>{try{const account=await api('/account');if(!alive)return;if(account.user?.role==='admin'){setState('ok');return}const[c,m]=await Promise.all([api('/kyc/config'),api('/kyc/me')]);if(!alive)return;const blocked=!!c.enabled&&m.kycStatus!=='VERIFIED';setState(blocked?'blocked':'ok');if(blocked)setWasBlocked(true);if(wasBlocked&&!blocked)setApproved(true)}catch{if(alive)setState('ok')}};check();const id=setInterval(check,5000);return()=>{alive=false;clearInterval(id)}},[wasBlocked]);if(state==='loading')return <VerificationLoader/>;if(state==='blocked')return <div className="kyc-gate"><div className="kyc-gate-card"><div className="kyc-gate-icon">✓</div><h1>KYC Verification Required</h1><p>Administrator has enabled mandatory KYC. Complete your Aadhaar + PAN verification before using the gateway.</p><button onClick={()=>{window.location.hash='dashboard/kyc'}}>Complete KYC</button><small>KYC fee is configured by the administrator.</small></div></div>;return <>{children}{approved&&<div className="kyc-popup"><div><div className="kyc-gate-icon">✓</div><h2>Your KYC Verified</h2><p>Your KYC has been successfully verified. You can now use the gateway.</p><button onClick={()=>setApproved(false)}>Continue</button></div></div>}</>}
createRoot(document.getElementById('root')).render(<React.StrictMode><Root/></React.StrictMode>);
