import React,{Suspense,lazy,useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import App from './App.jsx';
import OAuthBridge from './OAuthBridge.jsx';
import {api} from './api';
import './styles.css';
import './dashboard.css';
import './medium-typography.css';
import './kyc.css';
import './video-merchant.css';
import './payment-link-fix.css';
import './mobile-dashboard.css';

const GmailConnectMerchant=lazy(()=>import('./GmailConnectMerchant.jsx'));
const LegalPage=lazy(()=>import('./LegalPages.jsx'));
const Transactions=lazy(()=>import('./Transactions.jsx'));
const CheckoutRoutes=lazy(()=>import('./CheckoutRoutesV2.jsx'));
const PaymentLinkFixed=lazy(()=>import('./PaymentLinkFixed.jsx'));
const SubscriptionPage=lazy(()=>import('./SubscriptionPage.jsx'));
const AccountPage=lazy(()=>import('./AccountPage.jsx'));
const PasswordPage=lazy(()=>import('./PasswordPage.jsx'));
const KycPage=lazy(()=>import('./KycPage.jsx'));
const ApiPage=lazy(()=>import('./ApiPage.jsx'));
const MerchantApkPage=lazy(()=>import('./MerchantApkPage.jsx'));
const VideoMerchant=lazy(()=>import('./VideoMerchant.jsx'));
const Documentation=lazy(()=>import('./Documentation.jsx'));
const SupportTicketPage=lazy(()=>import('./SupportTicketPage.jsx'));
const FaqPage=lazy(()=>import('./FaqPage.jsx'));
const HomeLegalFooter=lazy(()=>import('./HomeLegalFooter.jsx'));

function RouteFallback(){return <div className="route-loading" role="status" aria-live="polite"><div className="route-loading-card"><div className="route-loading-logo">ϟ</div><div className="route-loading-spinner"/><b>Loading OmniUPI…</b><span>Preparing your secure workspace.</span></div></div>}
function SafeRoute({children}){return <Suspense fallback={<RouteFallback/>}>{children}</Suspense>}

function Root(){const[hash,setHash]=useState(window.location.hash);useEffect(()=>{const onHashChange=()=>setHash(window.location.hash);window.addEventListener('hashchange',onHashChange);return()=>window.removeEventListener('hashchange',onHashChange)},[]);const legal={'#privacy':'privacy','#terms':'terms','#refund':'refund','#shipping':'shipping','#contact':'contact'};const legalPaths={'/privacy-policy.html':'privacy','/terms.html':'terms','/refund-policy.html':'refund','/shipping-policy.html':'shipping','/contact.html':'contact'};if(legal[hash])return <SafeRoute><OAuthBridge/><LegalPage type={legal[hash]}/></SafeRoute>;if(legalPaths[window.location.pathname])return <SafeRoute><OAuthBridge/><LegalPage type={legalPaths[window.location.pathname]}/></SafeRoute>;if(window.location.pathname==='/auth')return <SafeRoute><OAuthBridge/><SubscriptionPage/></SafeRoute>;if(hash==='#dashboard/connect')return <SafeRoute><OAuthBridge/><KycGate><GmailConnectMerchant/></KycGate></SafeRoute>;if(hash==='#dashboard/account')return <SafeRoute><OAuthBridge/><AccountPage/></SafeRoute>;if(hash==='#dashboard/password')return <SafeRoute><OAuthBridge/><PasswordPage/></SafeRoute>;if(hash==='#dashboard/kyc')return <SafeRoute><OAuthBridge/><KycPage/></SafeRoute>;if(hash==='#dashboard/api')return <SafeRoute><OAuthBridge/><ApiPage/></SafeRoute>;if(hash==='#dashboard/apk')return <SafeRoute><OAuthBridge/><MerchantApkPage/></SafeRoute>;if(hash==='#dashboard/video')return <SafeRoute><OAuthBridge/><KycGate><VideoMerchant/></KycGate></SafeRoute>;if(hash==='#dashboard/docs')return <SafeRoute><OAuthBridge/><KycGate><Documentation/></KycGate></SafeRoute>;if(hash==='#dashboard/support')return <SafeRoute><OAuthBridge/><KycGate><SupportTicketPage/></KycGate></SafeRoute>;if(hash==='#dashboard/faq')return <SafeRoute><OAuthBridge/><KycGate><FaqPage/></KycGate></SafeRoute>;if(hash==='#subscription'||hash==='#dashboard/subscription')return <SafeRoute><OAuthBridge/><KycGate><SubscriptionPage/></KycGate></SafeRoute>;if(hash==='#dashboard/transactions')return <SafeRoute><OAuthBridge/><KycGate><Transactions onBack={()=>{window.location.hash='dashboard'}}/></KycGate></SafeRoute>;if(hash==='#dashboard/checkout')return <SafeRoute><OAuthBridge/><KycGate><CheckoutRoutes.CheckoutPage/></KycGate></SafeRoute>;if(hash==='#dashboard/payment-link')return <SafeRoute><OAuthBridge/><KycGate><PaymentLinkFixed.PaymentLinkPageFixed/></KycGate></SafeRoute>;if(hash.startsWith('#pay?'))return <SafeRoute><OAuthBridge/><PaymentLinkFixed.PublicPaymentPageFixed route={hash}/></SafeRoute>;if(hash==='#dashboard'||hash.startsWith('#dashboard/'))return <><OAuthBridge/><KycGate><App/></KycGate></>;return <><OAuthBridge/><App/><SafeRoute><HomeLegalFooter/></SafeRoute></>}

function VerificationLoader(){return <div className="omni-verification-loader" role="status" aria-live="polite"><style>{`.omni-verification-loader{position:fixed;inset:0;z-index:999999;display:grid;place-items:center;padding:20px;background:linear-gradient(145deg,#f4f6ff,#ecfffa);font-family:Inter,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.ovl-backdrop{position:absolute;inset:0;background:radial-gradient(circle at 50% 35%,#ffffffd9,transparent 58%)}.ovl-card{position:relative;width:min(410px,100%);padding:34px 26px 28px;border:1px solid #ffffffcc;border-radius:28px;background:#fffffff2;box-shadow:0 30px 90px #17213a20;text-align:center;backdrop-filter:blur(18px);animation:ovlIn .35s ease-out}.ovl-logo{width:68px;height:68px;margin:0 auto 16px;border-radius:21px;display:grid;place-items:center;color:#fff;font-size:37px;font-weight:950;background:linear-gradient(135deg,#6269e8,#19b99a);box-shadow:0 14px 30px #6269e84d}.ovl-spinner{height:30px;display:flex;justify-content:center;align-items:center;gap:6px;margin:5px 0 17px}.ovl-spinner i{width:7px;height:7px;border-radius:50%;background:#6269e8;animation:ovlDot 1.1s infinite ease-in-out}.ovl-spinner i:nth-child(2){animation-delay:.15s}.ovl-spinner i:nth-child(3){animation-delay:.3s}.ovl-eyebrow{font-size:10px;letter-spacing:.16em;font-weight:900;color:#6269e8}.ovl-card h1{margin:8px 0 8px;font-size:23px;color:#172033}.ovl-card p{margin:0 auto 19px;max-width:330px;color:#758094;font-size:13px;line-height:1.65}.ovl-progress{height:5px;background:#e9edf5;border-radius:99px;overflow:hidden;margin:0 auto 11px;max-width:300px}.ovl-progress span{display:block;width:42%;height:100%;border-radius:99px;background:linear-gradient(90deg,#6269e8,#19b99a);animation:ovlProgress 1.7s infinite ease-in-out}.ovl-card small{color:#9aa3b1;font-size:10px}@keyframes ovlDot{0%,80%,100%{transform:scale(.65);opacity:.45}40%{transform:scale(1.15);opacity:1}}@keyframes ovlProgress{0%{transform:translateX(-130%)}100%{transform:translateX(320%)}}@keyframes ovlIn{from{opacity:0;transform:translateY(8px) scale(.98)}to{opacity:1;transform:none}}@media(max-width:480px){.ovl-card{padding:30px 20px 25px;border-radius:24px}.ovl-card h1{font-size:21px}}`}</style><div className="ovl-backdrop"/><div className="ovl-card"><div className="ovl-logo"><span>ϟ</span></div><div className="ovl-spinner"><i/><i/><i/></div><div className="ovl-eyebrow">OMNIUPI SECURITY</div><h1>Checking account verification</h1><p>We're securely checking your account status. Please wait a moment.</p><div className="ovl-progress"><span/></div><small>Secure connection · Account verification in progress</small></div></div>}
function KycGate({children}){const[state,setState]=useState('loading');const[approved,setApproved]=useState(false);const[wasBlocked,setWasBlocked]=useState(false);useEffect(()=>{let alive=true;const check=async()=>{try{const account=await api('/account');if(!alive)return;if(account.user?.role==='admin'){setState('ok');return}const[c,m]=await Promise.all([api('/kyc/config'),api('/kyc/me')]);if(!alive)return;const blocked=!!c.enabled&&m.kycStatus!=='VERIFIED';setState(blocked?'blocked':'ok');if(blocked)setWasBlocked(true);if(wasBlocked&&!blocked)setApproved(true)}catch{if(alive)setState('ok')}};check();const id=setInterval(check,5000);return()=>{alive=false;clearInterval(id)}},[wasBlocked]);if(state==='loading')return <VerificationLoader/>;if(state==='blocked')return <div className="kyc-gate"><div className="kyc-gate-card"><div className="kyc-gate-icon">✓</div><h1>KYC Verification Required</h1><p>Administrator has enabled mandatory KYC. Complete your Aadhaar + PAN verification before using the gateway.</p><button onClick={()=>{window.location.hash='dashboard/kyc'}}>Complete KYC</button><small>KYC fee is configured by the administrator.</small></div></div>;return <>{children}{approved&&<div className="kyc-popup"><div><div className="kyc-gate-icon">✓</div><h2>Your KYC Verified</h2><p>Your KYC has been successfully verified. You can now use the gateway.</p><button onClick={()=>setApproved(false)}>Continue</button></div></div>}</>}
createRoot(document.getElementById('root')).render(<React.StrictMode><Root/></React.StrictMode>);
