import React,{useEffect,useMemo,useState} from 'react';
import {Check,Clock3,Copy,Download,ExternalLink,Link2,Menu,ShieldCheck,X,Zap,RefreshCw} from 'lucide-react';
import {api} from './api';

const LINKS_KEY='omniupi_payment_links_v2';
const DEFAULT={brandName:'OmniUPI',theme:'#0B95BD',instructions:'Pay using any supported UPI app.\nVerify the amount before completing payment.',showQr:true,showIntent:true,logo:''};
function read(k,f){try{const v=localStorage.getItem(k);return v?JSON.parse(v):f}catch{return f}}
function merchant(){try{const ms=JSON.parse(localStorage.getItem('seox_merchants')||'[]');return ms.find(x=>x.verified&&x.upiId)||ms.find(x=>x.upiId)||null}catch{return null}}
function merchantId(m){return m?._id||m?.id||null}
function Page({title,children}){return <div className="cx-page"><header><button onClick={()=>{location.hash='dashboard'}}><Menu size={25}/></button><button className="brandnav" onClick={()=>{location.hash='dashboard'}}><span>ϟ</span> OmniUPI</button><b>{title}</b><span className="trial">● 2-day Trial • Active</span></header><main>{children}</main></div>}
function Field({label,children}){return <label className="field"><b>{label}</b>{children}</label>}
function Warn({children}){return <div className="warn"><ShieldCheck size={18}/>{children}</div>}
function Stat({n,t}){return <div className="stat"><small>{t}</small><strong>{n}</strong></div>}

export function PaymentLinkPageFixed(){
 const m=merchant();
 const [customer,setCustomer]=useState(''),[mobile,setMobile]=useState(''),[amount,setAmount]=useState(''),[remark,setRemark]=useState('');
 const [links,setLinks]=useState(()=>read(LINKS_KEY,[])),[toast,setToast]=useState(''),[creating,setCreating]=useState(false),[checking,setChecking]=useState('');
 useEffect(()=>localStorage.setItem(LINKS_KEY,JSON.stringify(links)),[links]);
 const generate=async()=>{const n=Number(amount);if(!m?.upiId){setToast('Verify a merchant first. Payment will use only the verified UPI ID.');return}if(!customer.trim()||!/^[0-9]{10}$/.test(mobile)||!Number.isFinite(n)||n<1){setToast('Enter customer name, valid 10-digit mobile and amount.');return}if(creating)return;setCreating(true);setToast('Creating secure payment order…');try{const result=await api('/orders/payment-link',{method:'POST',body:JSON.stringify({merchantId:merchantId(m),customerMobile:mobile,amount:Number(n.toFixed(2)),remark:remark.trim()})});const order=result?.result;if(!order?.orderId||!order?.paymentUrl)throw new Error('Backend did not return a valid Order ID/payment URL.');const item={id:order.orderId,orderId:order.orderId,customer:customer.trim(),mobile,amount:Number(order.amount).toFixed(2),remark:remark.trim(),link:order.paymentUrl,createdAt:Date.now(),expires:new Date(order.expiresAt).getTime(),status:order.status||'PENDING',qrDataUrl:order.qrDataUrl||''};setLinks(p=>[item,...p.filter(x=>x?.orderId!==item.orderId)]);setCustomer('');setMobile('');setAmount('');setRemark('');setToast(`Payment link created. Order ID: ${order.orderId}`)}catch(error){setToast(error?.message||'Unable to create payment link. Please try again.')}finally{setCreating(false)}};
 const copy=async l=>{try{await navigator.clipboard.writeText(l);setToast('Payment link copied.')}catch{setToast('Copy failed')}};
 const openQr=l=>{if(l.qrDataUrl){window.open(l.qrDataUrl,'_blank','noopener,noreferrer');return}window.open(l.link,'_blank','noopener,noreferrer')};
 const check=async l=>{if(!l?.orderId||checking)return;setChecking(l.orderId);try{const r=await api(`/checkout/${encodeURIComponent(l.orderId)}/status?check=1`);const status=r?.result?.txnStatus||'PENDING';setLinks(p=>p.map(x=>x.orderId===l.orderId?{...x,status}:x));setToast(status==='SUCCESS'?`Payment verified successfully${r?.result?.utr?` • UTR: ${r.result.utr}`:''}`:`Payment status: ${status}`)}catch(e){setToast(e?.message||'Unable to check payment status.')}finally{setChecking('')}};
 return <Page title="Payment Link Management"><section className="cx-card"><div className="hero"><Link2 size={34}/><div><h1>Payment Link Management</h1><p>Create backend-backed links with real Order IDs.</p></div></div>{!m&&<Warn>Connect Merchant → Verify UPI ID before generating a link.</Warn>}{toast&&<div className="toast">{toast}<button onClick={()=>setToast('')}><X size={15}/></button></div>}<div className="stats"><Stat n="₹0.00" t="TODAY'S COLLECTION"/><Stat n={links.length} t="LINKS TODAY"/><Stat n="1" t="ACCOUNT"/><Stat n={links.length?'Active':'No Links'} t="STATUS"/></div><div className="form"><div className="formhead"><h2>＋ Create New Payment Link</h2><span>◷ Backend Order + Gmail verification · 5 min expiry</span></div><div className="grid2"><Field label="CUSTOMER NAME"><input value={customer} onChange={e=>setCustomer(e.target.value)} placeholder="Enter customer name"/></Field><Field label="MOBILE NUMBER"><input value={mobile} onChange={e=>setMobile(e.target.value.replace(/\D/g,'').slice(0,10))} placeholder="10-digit mobile"/></Field><Field label="AMOUNT (₹)"><input type="number" min="1" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="0.00"/></Field><Field label="REMARK (OPTIONAL)"><input value={remark} onChange={e=>setRemark(e.target.value)} placeholder="e.g. Gift, Deposit"/></Field></div><button className="primary" onClick={generate} disabled={creating}><Zap size={18}/>{creating?'Creating Order…':'Generate Link'}</button><p className="bind-note">Each link is created by the backend with a unique Order ID and expires after 5 minutes. Payment is matched against that exact Order ID and amount.</p></div><div className="form"><div className="formhead"><h2>☷ My Links</h2><span>Total: {links.length}</span></div>{!links.length?<div className="empty"><Link2 size={46}/><h3>No Links Found</h3><p>Create your first link to get started.</p></div>:links.map(l=><div className="linkrow" key={l.id}><div><b>{l.customer} • ₹{l.amount}</b><small>{l.orderId||l.id} • {new Date(l.createdAt).toLocaleString('en-IN')}</small><code>{l.link}</code><small className={l.status==='SUCCESS'?'status-success':l.status==='EXPIRED'?'status-expired':'status-pending'}>Status: {l.status||'PENDING'}</small></div><div className="actions"><button onClick={()=>copy(l.link)}><Copy size={15}/> Copy</button><button onClick={()=>openQr(l)}>QR</button><button onClick={()=>check(l)} disabled={checking===l.orderId}><RefreshCw size={15}/> {checking===l.orderId?'Checking…':'Check Payment'}</button><button onClick={()=>window.open(l.link,'_blank','noopener,noreferrer')}><ExternalLink size={15}/> Open</button></div></div>)}</div></section></Page>
}

function IntentButtons({href}){return <div className="intents"><a href={href}>◉ <b>PayTM</b><span>Pay via app ›</span></a><a href={href}>● <b>PhonePe</b><span>Pay via app ›</span></a><a href={href}>◉ <b>Google Pay</b><span>Pay via app ›</span></a></div>}
function Instructions({text}){const rows=(text||'').split('\n').map(x=>x.trim()).filter(Boolean);return rows.length?<div className="instructions"><b>Payment Instructions</b>{rows.map((x,i)=><div key={i}>✓ {x}</div>)}</div>:null}
function QrBlock({src,amount}){return <div className="qrblock"><b>▦ Scan & Pay</b><div><img src={src} alt="UPI QR Code for payment"/><div><small>Scan to pay exactly ₹{amount.toFixed(2)}</small><a href={src} target="_blank" rel="noreferrer"><Download size={15}/> Download QR</a></div></div></div>}

export function PublicPaymentPageFixed({route}){
 const q=useMemo(()=>new URLSearchParams(route.startsWith('#')?route.slice(5):route.slice(4)),[route]);
 const orderId=q.get('order_id');
 const [checkout,setCheckout]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[status,setStatus]=useState('PENDING'),[checking,setChecking]=useState(false),[toastText,setToastText]=useState(''),[seconds,setSeconds]=useState(300);
 const load=async()=>{if(!orderId){setError('This payment link is invalid.');setLoading(false);return}try{const r=await api(`/checkout/${encodeURIComponent(orderId)}`);const x=r?.result;if(!x)throw new Error('Payment link not found');setCheckout(x);setStatus(x.status||'PENDING');setSeconds(Math.max(0,Math.floor((new Date(x.expiresAt).getTime()-Date.now())/1000)))}catch(e){setError(e?.message||'Unable to load payment link.')}finally{setLoading(false)}};
 const checkPayment=async()=>{if(!orderId||checking)return;setChecking(true);try{const r=await api(`/checkout/${encodeURIComponent(orderId)}/status?check=1`);const x=r?.result;const next=x?.txnStatus||'PENDING';setStatus(next);if(next==='SUCCESS'&&x?.redirectUrl){setTimeout(()=>window.location.assign(x.redirectUrl),700)}else if(next==='SUCCESS'){setToastText('Payment verified successfully by Gmail.')}else if(next==='EXPIRED'){setToastText('Payment link expired.')}else{setToastText('Payment not received yet. Please wait a moment and check again.')}}catch(e){setToastText(e?.message||'Unable to verify payment right now.')}finally{setChecking(false)}};
 useEffect(()=>{load()},[orderId]);
 useEffect(()=>{if(!checkout||status!=='PENDING')return;const onVisible=()=>{if(document.visibilityState==='visible')checkPayment()};document.addEventListener('visibilitychange',onVisible);const timers=[1800,5000,10000].map(ms=>setTimeout(checkPayment,ms));return()=>{document.removeEventListener('visibilitychange',onVisible);timers.forEach(clearTimeout)}},[checkout?.orderId,status]);
 useEffect(()=>{if(!checkout||status!=='PENDING')return;const id=setInterval(()=>setSeconds(Math.max(0,Math.floor((new Date(checkout.expiresAt).getTime()-Date.now())/1000))),1000);return()=>clearInterval(id)},[checkout,status]);
 if(loading)return <PublicShell><div className="expired"><Clock3 size={44}/><h2>Loading secure payment…</h2><p>Preparing your payment QR and Order ID verification.</p></div></PublicShell>;
 if(error)return <PublicShell><div className="expired"><Clock3 size={50}/><h2>Payment Link Unavailable</h2><p>{error}</p></div></PublicShell>;
 if(status==='EXPIRED'||seconds<=0)return <PublicShell><div className="expired"><Clock3 size={50}/><h2>Payment Link Expired</h2><p>This payment link was valid for 5 minutes and can no longer be used.</p></div></PublicShell>;
 const s={...DEFAULT,...(checkout.checkout||{})};const amount=Number(checkout.amount||0);const intent=checkout.upiUrl||'';const qr=checkout.qrDataUrl||'';const theme=s.themeColor||DEFAULT.theme;const mm=String(Math.floor(seconds/60)).padStart(2,'0'),ss=String(seconds%60).padStart(2,'0');
 return <PublicShell><div className="public-card"><div className="public-top" style={{background:`linear-gradient(135deg,${theme},#6d4bc0)`}}><div className="brand">{s.brandLogo?<img src={s.brandLogo} alt=""/>:<span>▣</span>}<b>{s.brandName}</b><i>◷ {mm}:{ss}</i></div><small>Amount</small><strong>₹{amount.toFixed(2)}</strong></div><div className="public-body"><div className="request"><small>PAYMENT REQUEST</small><h2>Order #{checkout.orderId}</h2></div>{s.showQrCode&&qr&&<QrBlock src={qr} amount={amount}/>} {s.showIntentButtons&&<IntentButtons href={intent}/>}<Instructions text={s.instructions}/><div className="verification-box"><div><b>{status==='SUCCESS'?'✓ Payment Verified':'🔒 Secure Payment'}</b><small>{status==='SUCCESS'?'Gmail verification confirmed this payment.':'Your UPI ID is securely hidden. Payment is matched to this Order ID and amount.'}</small></div></div><button className="pay" onClick={checkPayment} disabled={checking}>{checking?<><RefreshCw size={18}/> Verifying Payment…</>:<><Check size={18}/> Check Payment</>}</button>{toastText&&<div className="status-toast">{toastText}</div>}<p className="fixed">🔒 Order ID: {checkout.orderId} • Automatic Gmail verification enabled • Link expires in 5 minutes</p></div></div></PublicShell>
}
function PublicShell({children}){return <div className="public-shell"><div className="public-logo"><span>ϟ</span><h1>OmniUPI</h1></div>{children}<small className="powered">Powered by OmniUPI</small></div>}
