import { useEffect, useState } from 'react';
import { ArrowLeft, CheckCircle2, Clock3, MessageSquare, Plus, Send, Ticket, X } from 'lucide-react';
import { api } from './api';

const categories = [['payment','Payment'],['api','API'],['kyc','KYC'],['account','Account'],['technical','Technical'],['other','Other']];
const styles = {
  page:{minHeight:'100vh',background:'#f4f6fa',fontFamily:'Inter,system-ui,sans-serif',color:'#273145'},
  top:{position:'sticky',top:0,zIndex:10,display:'flex',alignItems:'center',gap:12,padding:'15px 16px',background:'#fff',borderBottom:'1px solid #e7eaf0'},
  back:{border:0,background:'#f1f3f7',width:40,height:40,borderRadius:12,display:'grid',placeItems:'center',color:'#4f5bd5'},
  wrap:{maxWidth:760,margin:'0 auto',padding:'22px 15px 40px'},
  card:{background:'#fff',border:'1px solid #e5e9f0',borderRadius:20,boxShadow:'0 10px 30px rgba(35,45,70,.06)',padding:18,marginBottom:15},
  primary:{border:0,borderRadius:12,padding:'12px 16px',background:'linear-gradient(135deg,#5364e8,#4a55d6)',color:'#fff',fontWeight:800,fontSize:15,display:'inline-flex',alignItems:'center',gap:8},
  input:{width:'100%',boxSizing:'border-box',border:'1px solid #dfe4ec',borderRadius:12,padding:'13px',fontSize:15,outline:0,background:'#fff'},
};

export default function SupportTicketPage(){
  const [tickets,setTickets]=useState([]),[loading,setLoading]=useState(true),[selected,setSelected]=useState(null),[showForm,setShowForm]=useState(false),[error,setError]=useState('');
  const load=async()=>{try{setLoading(true);const d=await api('/support/tickets');setTickets(d.tickets||[]);if(selected){const fresh=(d.tickets||[]).find(t=>t._id===selected._id);if(fresh)setSelected(fresh)}}catch(e){setError(e.message||'Unable to load tickets')}finally{setLoading(false)}};
  useEffect(()=>{load()},[]);
  if(selected)return <TicketConversation ticket={selected} onBack={()=>{setSelected(null);load()}}/>;
  return <div style={styles.page}><header style={styles.top}><button style={styles.back} onClick={()=>{window.location.hash='dashboard'}}><ArrowLeft size={20}/></button><div><b style={{fontSize:18}}>Support Tickets</b><div style={{fontSize:12,color:'#7b8494'}}>Manage your support requests</div></div><div style={{marginLeft:'auto'}}><button style={styles.primary} onClick={()=>setShowForm(true)}><Plus size={17}/> New Ticket</button></div></header><main style={styles.wrap}>{error&&<div style={{...styles.card,color:'#b42318',background:'#fff5f5'}}>{error}</div>}{showForm&&<NewTicket onCreated={async t=>{setShowForm(false);await load();setSelected(t)}} onCancel={()=>setShowForm(false)}/>} {!showForm&&<>{loading?<div style={{...styles.card,textAlign:'center',padding:45}}>Loading tickets…</div>:tickets.length===0?<div style={{...styles.card,textAlign:'center',padding:'55px 20px'}}><div style={{width:64,height:64,borderRadius:18,background:'#eef0ff',color:'#4d5bd6',display:'grid',placeItems:'center',margin:'0 auto 18px'}}><Ticket size={34}/></div><h2 style={{margin:'0 0 8px'}}>No tickets found</h2><p style={{margin:'0 auto 24px',maxWidth:420,color:'#7d8797'}}>You haven't created any support tickets yet.</p><button style={{...styles.primary,padding:'14px 22px'}} onClick={()=>setShowForm(true)}><Plus size={19}/> Create First Ticket</button></div>:<div>{tickets.map(t=><TicketCard key={t._id} ticket={t} onClick={()=>setSelected(t)}/>)}</div>}</>}</main></div>;
}

function NewTicket({onCreated,onCancel}){const[subject,setSubject]=useState(''),[category,setCategory]=useState('technical'),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');const submit=async e=>{e.preventDefault();setError('');if(!subject.trim()||!message.trim())return setError('Subject and message are required.');try{setBusy(true);const d=await api('/support/tickets',{method:'POST',body:JSON.stringify({subject,category,message})});onCreated(d.ticket)}catch(e){setError(e.message||'Unable to create ticket')}finally{setBusy(false)}};return <div style={styles.card}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:18}}><div><h2 style={{margin:0,fontSize:20}}>Create New Ticket</h2><p style={{margin:'5px 0 0',color:'#7d8797',fontSize:13}}>Our support team will review your request.</p></div><button style={styles.back} onClick={onCancel}><X size={19}/></button></div><form onSubmit={submit} style={{display:'grid',gap:14}}><label style={{fontWeight:750,fontSize:13}}>Subject<input style={{...styles.input,marginTop:7}} value={subject} onChange={e=>setSubject(e.target.value)} maxLength={160} placeholder="e.g. Payment not received"/></label><label style={{fontWeight:750,fontSize:13}}>Category<select style={{...styles.input,marginTop:7}} value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label style={{fontWeight:750,fontSize:13}}>Message<textarea style={{...styles.input,marginTop:7,minHeight:140,resize:'vertical'}} value={message} onChange={e=>setMessage(e.target.value)} maxLength={5000} placeholder="Explain your issue clearly…"/></label>{error&&<div style={{color:'#b42318',fontSize:13}}>{error}</div>}<button style={styles.primary} disabled={busy}>{busy?'Creating…':<><Send size={17}/> Create Ticket</>}</button></form></div>}

function TicketCard({ticket,onClick}){const last=ticket.messages?.[ticket.messages.length-1];return <button onClick={onClick} style={{...styles.card,width:'100%',textAlign:'left',cursor:'pointer',display:'block'}}><div style={{display:'flex',gap:12,alignItems:'flex-start'}}><div style={{width:45,height:45,borderRadius:13,background:'#eef0ff',color:'#4d5bd6',display:'grid',placeItems:'center',flexShrink:0}}><MessageSquare size={22}/></div><div style={{minWidth:0,flex:1}}><div style={{display:'flex',justifyContent:'space-between',gap:10}}><b style={{overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap'}}>{ticket.subject}</b><Status status={ticket.status}/></div><div style={{fontSize:12,color:'#7c8696',marginTop:5}}>{ticket.ticketId} · {ticket.category} · {ticket.priority}</div><p style={{margin:'9px 0 0',color:'#697487',fontSize:13,overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap'}}>{last?.text||'No messages'}</p></div></div></button>}

function Status({status}){const map={pending:['#fff5d8','#9a6b00','Pending'],open:['#e9efff','#4b5fd1','Open'],waiting_user:['#eaf8f4','#16806b','Waiting for you'],resolved:['#eaf8ee','#218b4b','Resolved'],closed:['#f0f1f4','#697180','Closed']};const [bg,color,label]=map[status]||map.pending;return <span style={{background:bg,color,padding:'5px 9px',borderRadius:999,fontSize:11,fontWeight:850,whiteSpace:'nowrap'}}>{label}</span>}

function TicketConversation({ticket,onBack}){const[current,setCurrent]=useState(ticket),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');const refresh=async()=>{const d=await api(`/support/tickets/${current._id}`);setCurrent(d.ticket)};const send=async e=>{e.preventDefault();if(!message.trim())return;try{setBusy(true);await api(`/support/tickets/${current._id}/messages`,{method:'POST',body:JSON.stringify({message})});setMessage('');await refresh()}catch(e){setError(e.message||'Unable to send message')}finally{setBusy(false)}};return <div style={styles.page}><header style={styles.top}><button style={styles.back} onClick={onBack}><ArrowLeft size={20}/></button><div style={{minWidth:0}}><b style={{fontSize:17,display:'block',overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap'}}>{current.subject}</b><span style={{fontSize:12,color:'#7b8494'}}>{current.ticketId} · <Status status={current.status}/></span></div></header><main style={styles.wrap}><div style={styles.card}><div style={{display:'flex',justifyContent:'space-between',gap:12,flexWrap:'wrap'}}><div><span style={{fontSize:12,color:'#7d8797'}}>CATEGORY</span><div style={{fontWeight:800,textTransform:'capitalize'}}>{current.category}</div></div><div><span style={{fontSize:12,color:'#7d8797'}}>PRIORITY</span><div style={{fontWeight:800,textTransform:'capitalize'}}>{current.priority}</div></div><div><span style={{fontSize:12,color:'#7d8797'}}>STATUS</span><div><Status status={current.status}/></div></div></div></div><div style={{...styles.card,padding:12}}><div style={{display:'grid',gap:10}}>{(current.messages||[]).map(m=><div key={m._id} style={{display:'flex',justifyContent:m.sender==='user'?'flex-end':'flex-start'}}><div style={{maxWidth:'82%',padding:'11px 13px',borderRadius:16,background:m.sender==='user'?'#5364e8':'#f0f2f6',color:m.sender==='user'?'#fff':'#303b4e'}}><div style={{fontSize:11,fontWeight:800,opacity:.75,marginBottom:4}}>{m.sender==='user'?'You':'Support'}</div><div style={{whiteSpace:'pre-wrap',lineHeight:1.45,fontSize:14}}>{m.text}</div><div style={{fontSize:10,opacity:.65,marginTop:6}}>{new Date(m.createdAt).toLocaleString()}</div></div></div>)}</div></div>{current.status!=='closed'&&current.status!=='resolved'&&<form onSubmit={send} style={{...styles.card,display:'flex',gap:9,alignItems:'flex-end'}}><textarea style={{...styles.input,minHeight:50,resize:'vertical'}} value={message} onChange={e=>setMessage(e.target.value)} placeholder="Write a reply…" maxLength={5000}/><button style={{...styles.primary,height:48}} disabled={busy}>{busy?<Clock3 size={17}/>:<Send size={17}/>}</button></form>}{error&&<div style={{...styles.card,color:'#b42318'}}>{error}</div>}{(current.status==='resolved'||current.status==='closed')&&<div style={{...styles.card,textAlign:'center',color:'#218b4b'}}><CheckCircle2 size={24}/><b style={{display:'block',marginTop:7}}>This ticket has been {current.status}.</b></div>}</main></div>}
